"""Select the benchmark candidate corpus, and render what was selected.

Offline (ADR-040): renders the `bench/CANDIDATES.md` block from `bench/candidates.yaml`, the
scan records and the pack.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from collections.abc import Iterable, Sequence
from pathlib import Path
from typing import Any, NamedTuple

import yaml

# Shared with the gate-1 scorer, so both agree on what a usage is.
from gate1_score import ACTIONABLE_KINDS

from obelize.packs import loader
from obelize.scan import manifests

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "bench" / "candidates.yaml"
DOCUMENT = ROOT / "bench" / "CANDIDATES.md"
FRAME = ROOT / "bench" / "gate1" / "sample.yaml"
FRAME_SCAN = ROOT / "bench" / "results" / "gate1" / "scan.json"
DRAWN_SCAN = ROOT / "bench" / "results" / "candidates" / "scan.json"

MARKERS = (
    "<!-- candidates:begin -- generated by bench/candidates.py; edit that, not this -->",
    "<!-- candidates:end -->",
)

# docs/BENCHMARK.md's anti-inflation cap, applied to candidates (ADR-040 D6).
MAX_PER_OWNER = 2

# No licence, or one GitHub could not identify: neither lets the benchmark quote.
UNLICENSED: frozenset[str] = frozenset({"none", "NOASSERTION"})

# A short SHA is a prefix, resolved against whatever the repository holds that day.
FULL_SHA = re.compile(r"^[0-9a-f]{40}$")

# Closed, so rejections can be counted and audited.
REASONS: tuple[str, ...] = (
    "unlicensed",
    "fork",
    "gone",
    "larger_than_cap",
    "owner_at_limit",
    "development_corpus",
    "no_finding",
    "vendors_the_sdk",
)

SKIP_REASONS: tuple[str, ...] = (
    *REASONS,
    "already_a_candidate",
    "no_such_finding",
    "scan_failed",
    "clone_budget_spent",
)

# How a surface with no candidate behind it was resolved (ADR-040 D5).
OUTCOMES: tuple[str, ...] = ("drawn", "no_eligible_result", "absent")

# Path evidence of a test suite, in table order; whether it covers the change is a reviewer's call.
EVIDENCE: tuple[str, ...] = ("test_files", "test_config", "ci_workflow", "manifest")

# pytest's two naming conventions, or any Python file under `test/` or `tests/`.
TEST_FILE = re.compile(
    r"(?:^|/)(?:test_[^/]+\.py|[^/]+_test\.py)$|(?:^|/)tests?/(?:.+/)?[^/]+\.py$"
)

TEST_CONFIG: frozenset[str] = frozenset({"conftest.py", "noxfile.py", "pytest.ini", "tox.ini"})

# Where an `install` command can be read rather than guessed.
CI_WORKFLOW = re.compile(r"^\.github/workflows/[^/]+\.ya?ml$")

# Vendored SDK source: a case there would migrate the SDK, not an application.
VENDORED = re.compile(r"(?:^|/)google/generativeai/")


class Surface(NamedTuple):
    """A pack change and the legacy names a finding carries when it meets it."""

    change: str
    kind: str
    symbols: tuple[str, ...]
    patterns: tuple[str, ...]


class Corpus(NamedTuple):
    data: dict[str, Any]
    records: dict[str, dict[str, Any]]
    surfaces: tuple[Surface, ...]


def surfaces() -> tuple[Surface, ...]:
    """Each pack change's legacy symbols, via the loader the scanner uses."""
    from obelize.cli import DEFAULT_PACK

    found: list[Surface] = []
    for change in loader.load(DEFAULT_PACK).pack.changes:
        params: dict[str, Any] = change.params.model_dump()
        symbols: set[str] = set()
        if change.kind == "rename_import":
            symbols.add(params["from_module"])
            symbols |= {f"{params['from_module']}.{name}" for name in params["submodule_map"]}
        elif change.kind == "generative_model_calls":
            symbols.add(params["ctor_symbol"])
            for receiver, methods in params["methods"].items():
                symbols |= {f"{receiver}.{method}" for method in methods}
        elif change.kind == "flag_only":
            symbols |= set(params.get("symbols") or ())
            symbols |= set(params.get("attributes") or ())
        elif change.kind == "manifest_dependency":
            symbols.add(params["from_name"])
        else:
            symbols.add(params["legacy_symbol"])
        found.append(
            Surface(
                change=change.id,
                kind=change.kind,
                symbols=tuple(sorted(symbols)),
                patterns=tuple(sorted(params.get("patterns") or ())),
            )
        )
    return tuple(found)


def exercises(findings: Iterable[dict[str, Any]], surface: Surface) -> bool:
    """Whether findings meet `surface` by symbol, or by `confidence_reason` for pattern changes."""
    return any(
        row["symbol"] in surface.symbols or row["confidence_reason"] in surface.patterns
        for row in findings
    )


def vendors(findings: Iterable[dict[str, Any]]) -> bool:
    return any(VENDORED.search(row["path"]) for row in findings)


def pattern_key(findings: Iterable[dict[str, Any]]) -> tuple[str, ...]:
    """Sorted legacy symbols, over call sites only."""
    return tuple(sorted({row["symbol"] for row in findings if row["kind"] in ACTIONABLE_KINDS}))


def evidence(paths: Iterable[str]) -> dict[str, str]:
    """Each evidence word with the first path that showed it."""
    witness: dict[str, str] = {}
    for path in paths:
        if "test_files" not in witness and TEST_FILE.search(path):
            witness["test_files"] = path
        if "test_config" not in witness and path.rsplit("/", 1)[-1] in TEST_CONFIG:
            witness["test_config"] = path
        if "ci_workflow" not in witness and CI_WORKFLOW.match(path):
            witness["ci_workflow"] = path
        if "manifest" not in witness and manifests.is_manifest(path):
            witness["manifest"] = path
    return {word: witness[word] for word in EVIDENCE if word in witness}


def load() -> Corpus:
    data = yaml.safe_load(DATA.read_text(encoding="utf-8"))
    records: dict[str, dict[str, Any]] = {}
    for path in (FRAME_SCAN, DRAWN_SCAN):
        for record in json.loads(path.read_text(encoding="utf-8"))["scanned"]:
            records[record["full_name"]] = record
    return Corpus(data=data, records=records, surfaces=surfaces())


def found(corpus: Corpus, name: str) -> list[dict[str, Any]]:
    record: list[dict[str, Any]] = corpus.records[name]["findings"]
    return record


def _rows(corpus: Corpus) -> list[dict[str, Any]]:
    return list(corpus.data["candidates"])


def _candidate_table(corpus: Corpus) -> list[str]:
    lines = [
        "| # | Repository | Owner | SPDX | SHA | Stars | Findings | Eligible | Symbols | "
        "Tests | Drawn as |",
        "|---:|---|---|---|---|---:|---:|---:|---:|---|---|",
    ]
    for number, row in enumerate(_rows(corpus), start=1):
        name = row["full_name"]
        rows = found(corpus, name)
        tests = ", ".join(f"`{word}`" for word in row["tests"]) or "--"
        lines.append(
            f"| {number} | [{name}]({row['url']}) | `{row['owner']}` | `{row['license']}` | "
            f"`{row['sha']}` | {row['stars']} | {len(rows)} | "
            f"{corpus.records[name]['counts']['eligible']} | {len(pattern_key(rows))} | "
            f"{tests} | {row['source']} |"
        )
    return lines


def _surface_table(corpus: Corpus) -> list[str]:
    resolution = {row["change"]: row for row in corpus.data["surfaces"]}
    lines = [
        "| Change | Legacy names | Candidates | How it is resolved |",
        "|---|---:|---:|---|",
    ]
    for surface in corpus.surfaces:
        hits = [
            row["full_name"]
            for row in _rows(corpus)
            if exercises(found(corpus, row["full_name"]), surface)
        ]
        named = len(surface.symbols) + len(surface.patterns)
        if hits:
            how = f"exercised by {len(hits)}, first `{sorted(hits)[0]}`"
        else:
            drawn = resolution[surface.change]
            how = f"{drawn['outcome'].replace('_', ' ')}, {drawn['hits']} hit(s) searched"
        lines.append(f"| `{surface.change}` | {named} | {len(hits)} | {how} |")
    return lines


def _query_table(corpus: Corpus) -> list[str]:
    lines = [
        "| Change | Query | Hits | Examined | Outcome | Drawn | Why the rest were passed over |",
        "|---|---|---:|---:|---|---|---|",
    ]
    for row in corpus.data["surfaces"]:
        drawn = f"`{row['drawn']}`" if row["drawn"] else "--"
        counted = Counter(entry["reason"] for entry in row["skipped"])
        passed = "; ".join(f"{count} {reason}" for reason, count in counted.most_common())
        lines.append(
            f"| `{row['change']}` | `{row['query']}` | {row['hits']} | {row['examined']} | "
            f"`{row['outcome']}` | {drawn} | {passed} |"
        )
    return lines


def _unnamed_table(corpus: Corpus) -> list[str]:
    """Call sites no pack change names; not manifest rows, which may name the new distribution."""
    named = {symbol for surface in corpus.surfaces for symbol in surface.symbols}
    seen: Counter[str] = Counter()
    repositories: dict[str, set[str]] = {}
    for row in _rows(corpus):
        for finding in found(corpus, row["full_name"]):
            if finding["symbol"] in named or finding["kind"] not in ACTIONABLE_KINDS:
                continue
            seen[finding["symbol"]] += 1
            repositories.setdefault(finding["symbol"], set()).add(row["full_name"])
    lines = ["| Legacy name | Candidates | Call sites |", "|---|---:|---:|"]
    for symbol, total in sorted(seen.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"| `{symbol}` | {len(repositories[symbol])} | {total} |")
    return lines


def _rejection_table(corpus: Corpus) -> list[str]:
    counted = Counter(row["reason"] for row in corpus.data["rejected"])
    lines = ["| Reason | Repositories |", "|---|---:|"]
    for reason in REASONS:
        lines.append(f"| `{reason}` | {counted.get(reason, 0)} |")
    return lines


def _evidence_table(corpus: Corpus) -> list[str]:
    counted = Counter(word for row in _rows(corpus) for word in row["tests"])
    lines = ["| Evidence | Candidates |", "|---|---:|"]
    for word in EVIDENCE:
        lines.append(f"| `{word}` | {counted.get(word, 0)} |")
    return lines


def _pins(record: dict[str, Any], symbol: str) -> set[tuple[str, int]]:
    return {
        (row["path"], row["line"])
        for row in record["findings"]
        if row["kind"] == "manifest" and row["symbol"] == symbol
    }


def declares_the_new_sdk(corpus: Corpus) -> list[str]:
    """Repositories pinning `google-genai` where no legacy pin sits.

    A row at a legacy pin's position is `manifest-dependency`'s proposed add, not a declaration.
    """
    return sorted(
        name
        for name, record in corpus.records.items()
        if _pins(record, "google-genai") - _pins(record, "google-generativeai")
    )


def proposes_the_new_sdk(corpus: Corpus) -> list[str]:
    """Every scanned repository whose `google-genai` rows are all derived adds."""
    return sorted(
        name
        for name, record in corpus.records.items()
        if _pins(record, "google-genai")
        and not (_pins(record, "google-genai") - _pins(record, "google-generativeai"))
    )


def _declares_sentence(corpus: Corpus) -> str:
    declared = declares_the_new_sdk(corpus)
    proposed = proposes_the_new_sdk(corpus)
    total = len(corpus.records)
    named = {row["full_name"] for row in _rows(corpus)}
    head = (
        f"None of the {total} repositories scanned declares the new distribution in a "
        "manifest of its own."
        if not declared
        else f"{len(declared)} of the {total} repositories scanned declare the new "
        "distribution in a manifest of their own: "
        + ", ".join(f"`{name}`" for name in declared)
        + ". Where one of those is also a candidate the pin is new and the code is not, "
        "which is the manifest/code mismatch "
        "[BENCHMARK.md](../docs/BENCHMARK.md#negative-controls) names as a false-positive "
        "trap: "
        + (", ".join(f"`{name}`" for name in declared if name in named) or "none of them")
        + "."
    )
    if not proposed:
        return head
    return (
        f"{head} {len(proposed)} carry a `google-genai` row all the same, and every one of "
        "them sits at the same path and line as a legacy pin: it is the dependency "
        "`manifest-dependency` proposes to **add** where it removes the old one, not "
        "something the repository wrote. Counting those rows as declarations was this "
        "document's first reading of the scans, and it was wrong, which is why the "
        "manifest/code mismatch has to be drawn for rather than inherited from this corpus."
    )


def _rule_table(corpus: Corpus) -> list[str]:
    rows = _rows(corpus)
    owners = Counter(row["owner"] for row in rows)
    checks = (
        (
            "Every row carries a URL, an owner, an SPDX identifier and a full 40-character SHA",
            all(row["url"] and row["owner"] and row["license"] not in UNLICENSED for row in rows)
            and all(FULL_SHA.match(row["sha"]) for row in rows),
        ),
        ("No row is a fork", not any(row["fork"] for row in rows)),
        (f"At most {MAX_PER_OWNER} rows share an owner", max(owners.values()) <= MAX_PER_OWNER),
        (
            "Every row has a scan record at the SHA it pins",
            all(corpus.records.get(row["full_name"], {}).get("sha") == row["sha"] for row in rows),
        ),
        ("At least twenty rows", len(rows) >= 20),
    )
    lines = ["| Rule | Holds |", "|---|---|"]
    for text, holds in checks:
        lines.append(f"| {text} | {'yes' if holds else '**no**'} |")
    return lines


def render(corpus: Corpus) -> str:
    rows = _rows(corpus)
    data = corpus.data
    keys = {pattern_key(found(corpus, row["full_name"])) for row in rows}
    testable = [row for row in rows if "test_files" in row["tests"]]
    drawn = [row for row in rows if row["source"] != "frame"]
    lines = [
        f"{len(rows)} candidates, drawn {data['drawn_at']} from "
        f"{data['frame']['repositories']} repositories in the gate-1 frame "
        f"(`{data['frame']['sample']}`, {data['frame']['licensed']} of them licensed) plus "
        f"{len(drawn)} drawn for pack surfaces the frame did not exercise. Every row carries "
        "a URL, its owner, an SPDX identifier and the full SHA its scan record is at.",
        "",
        f"Checked against GitHub on {data['drawn_at']}, and scanned with obelize "
        f"{data['instrument']['obelize_version']} against pack "
        f"`{data['instrument']['pack']}` sha256 "
        f"`{data['instrument']['pack_sha256'][:16]}...`. The findings columns are read from "
        "`bench/results/gate1/scan.json` and `bench/results/candidates/scan.json`, which are "
        "dated artefacts: nothing re-fetches these checkouts on CI.",
        "",
        "**The rules, as applied.** Computed over the rows below, not asserted about them.",
        "",
        *_rule_table(corpus),
        "",
        "**The candidates.** `Findings` and `Eligible` are what the scanner reported at that "
        "SHA; `Symbols` is the size of the case's `pattern_key`; `Tests` is path evidence at "
        "that SHA, recorded against the first path that showed each word and never a "
        "judgement about whether the tests are any good.",
        "",
        *_candidate_table(corpus),
        "",
        f"The {len(rows)} candidates carry **{len(keys)} distinct pattern keys**, which is the "
        "denominator the headline is reported over a second time. "
        f"**{len(testable)} of {len(rows)}** carry a Python test file, so that is the ceiling "
        "on `verified_success` before a single case is written.",
        "",
        *_evidence_table(corpus),
        "",
        "**What the pack's changes meet.** A change is exercised when a finding at a "
        "candidate's pinned SHA carries one of the legacy names its own parameters state.",
        "",
        *_surface_table(corpus),
        "",
        "**The queries behind the rows that needed one.** Dated, verbatim, with the count "
        "GitHub returned. `absent` and `no eligible result` are different findings and are "
        "not interchangeable.",
        "",
        *_query_table(corpus),
        "",
        "**Call sites whose legacy name no change in the pack names.** Real usage the pack "
        "is silent about, which is material for the error analysis rather than a defect in "
        "this corpus.",
        "",
        *_unnamed_table(corpus),
        "",
        f"**Why the other {len(data['rejected'])} repositories in the frame are not "
        "candidates.** Published, because a corpus that shows only what it kept is a corpus "
        "whose selection nobody can audit.",
        "",
        *_rejection_table(corpus),
        "",
        f"**What declares `google-genai`.** {_declares_sentence(corpus)}",
    ]
    return "\n".join(lines)


def block(text: str) -> str:
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no candidates block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Render the candidate corpus.")
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    arguments = parser.parse_args(argv)
    generated = render(load())
    if not arguments.check:
        print(generated)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) == generated:
        print(f"{DOCUMENT.name} is up to date with bench/candidates.yaml")
        return 0
    print(f"{DOCUMENT.name} is stale; run `python bench/candidates.py` and paste the block")
    return 1


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    sys.exit(main())
