"""Turn the candidate corpus into benchmark cases, and render what was turned.

Offline (ADR-041): renders the `bench/CASES.md` block from `bench/cases.yaml`, the corpus,
draws and scans; the hand-written ground truth is only scored against the scanner.

Usage::

    python bench/cases.py            # print the block
    python bench/cases.py --check    # exit 1 if the document is stale
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import sys
from collections import Counter
from collections.abc import Iterable
from pathlib import Path
from typing import Any, NamedTuple

import candidates
import yaml

# Shared with the gate-1 scorer, so both agree on what a usage is.
from gate1_score import ACTIONABLE_KINDS

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "bench" / "cases.yaml"
DRAWS = ROOT / "bench" / "cases_draws.yaml"
DOCUMENT = ROOT / "bench" / "CASES.md"
DRAWN_SCAN = ROOT / "bench" / "results" / "cases" / "scan.json"

MARKERS = (
    "<!-- cases:begin -- generated by bench/cases.py; edit that, not this -->",
    "<!-- cases:end -->",
)

# A negative control may not produce these; a legacy pin is something to migrate too.
CONTROL_KINDS: frozenset[str] = ACTIONABLE_KINDS | {"manifest"}

DRAW_SKIP_REASONS: tuple[str, ...] = (
    *candidates.SKIP_REASONS,
    "no_test_file",
    "not_a_control",
    "no_witness",
)

# `auto`: the edit follows from the code alone; `manual`: it does not, and says why.
LABELS: tuple[str, ...] = ("auto", "manual")

SPLITS: tuple[str, ...] = ("dev", "holdout")
HOLDOUT_SHARE = 1 / 3

# A full uv key: a bare `3.12` can resolve to different builds.
DEFAULT_PYTHON = "cpython-3.12.9-macos-aarch64-none"

# Anything shorter than the full key is a request, not a pin.
INTERPRETER_KEY = re.compile(r"^cpython-\d+\.\d+\.\d+-[a-z]+-[a-z0-9_]+-[a-z]+$")

EXACT_VERSION = re.compile(r"^\d+\.\d+\.\d+$")

CALL_SITE = re.compile(r"^(?P<path>[^:]+):(?P<line>\d+):(?P<symbol>[^:]+):(?P<label>auto|manual)$")


class Corpus(NamedTuple):
    cases: dict[str, Any]
    draws: dict[str, Any]
    repositories: dict[str, dict[str, Any]]
    findings: dict[str, list[dict[str, Any]]]


def repositories() -> dict[str, dict[str, Any]]:
    corpus = yaml.safe_load(candidates.DATA.read_text(encoding="utf-8"))
    rows = {row["full_name"]: row for row in corpus["candidates"]}
    if DRAWS.exists():
        drawn = yaml.safe_load(DRAWS.read_text(encoding="utf-8"))
        for row in drawn["drawn"]:
            rows[row["full_name"]] = row
    return rows


def findings() -> dict[str, list[dict[str, Any]]]:
    found: dict[str, list[dict[str, Any]]] = {}
    for path in (candidates.FRAME_SCAN, candidates.DRAWN_SCAN, DRAWN_SCAN):
        if not path.exists():
            continue
        for record in json.loads(path.read_text(encoding="utf-8"))["scanned"]:
            if "error" in record:
                continue
            found[record["full_name"]] = record["findings"]
    return found


def is_control(row: dict[str, Any]) -> bool:
    return str(row["source"]).startswith("control:")


def testable(row: dict[str, Any]) -> bool:
    """Whether the pinned tree has a test file: the only way to reach `verified_success`."""
    return "test_files" in row["tests"]


# docs/BENCHMARK.md's minimum; each case costs a hand-written answer key.
CASE_COUNT = 20


def chosen(rows: dict[str, dict[str, Any]], found: dict[str, list[dict[str, Any]]]) -> list[str]:
    """Pick up to `CASE_COUNT` cases by a fixed rule, never by content (ADR-041 D3).

    Order: test files, surface draws, sole witnesses, new scanner keys, a systematic sample.
    """
    pool = {name: row for name, row in rows.items() if not is_control(row)}
    order = sorted(pool)
    picked: list[str] = []

    def take(name: str) -> None:
        if name not in picked and len(picked) < CASE_COUNT:
            picked.append(name)

    for name in order:
        if testable(pool[name]):
            take(name)
    for name in order:
        if str(pool[name]["source"]).startswith("surface:"):
            take(name)
    for surface in candidates.surfaces():
        witnesses = [name for name in order if candidates.exercises(found.get(name, []), surface)]
        if len(witnesses) == 1:
            take(witnesses[0])
    seen = {candidates.pattern_key(found.get(name, [])) for name in picked}
    for name in order:
        key = candidates.pattern_key(found.get(name, []))
        if key not in seen:
            seen.add(key)
            take(name)
    rest = [name for name in order if name not in picked]
    needed = CASE_COUNT - len(picked)
    if needed > 0 and rest:
        # ceil(len(rest) / step) >= needed, so one pass fills the quota or exhausts `rest`.
        step = max(1, len(rest) // needed)
        for index in range(0, len(rest), step):
            take(rest[index])
    return picked


def split(rows: dict[str, dict[str, Any]], picked: Iterable[str]) -> dict[str, str]:
    """Whole owners to `holdout` by `sha256(full_name)` until each stratum holds a third.

    Stratified on `testable`, so the dev set keeps cases it can verify (ADR-041 D5).
    """
    sides: dict[str, str] = {}
    picked = list(picked)
    for stratum in (True, False):
        members = [name for name in picked if testable(rows[name]) is stratum]
        owners: list[str] = []
        for name in sorted(members, key=lambda one: hashlib.sha256(one.encode()).hexdigest()):
            if rows[name]["owner"] not in owners:
                owners.append(rows[name]["owner"])
        wanted = math.ceil(len(members) * HOLDOUT_SHARE)
        holdout: set[str] = set()
        held = 0
        for owner in owners:
            if held >= wanted:
                break
            holdout.add(owner)
            held += sum(1 for name in members if rows[name]["owner"] == owner)
        for name in members:
            sides[name] = "holdout" if rows[name]["owner"] in holdout else "dev"
    return sides


# Licences docs/BENCHMARK.md keeps a `patch.diff` for; others are metrics-only.
PERMISSIVE: frozenset[str] = frozenset({"MIT", "BSD-2-Clause", "BSD-3-Clause", "Apache-2.0", "ISC"})


def load() -> Corpus:
    return Corpus(
        cases=yaml.safe_load(DATA.read_text(encoding="utf-8")),
        draws=yaml.safe_load(DRAWS.read_text(encoding="utf-8")),
        repositories=repositories(),
        findings=findings(),
    )


def sites(case: dict[str, Any]) -> list[dict[str, Any]]:
    return list(case["ground_truth"]["call_sites"])


def labelled(case: dict[str, Any]) -> Counter[Any]:
    from gate1_score import rows

    return rows(sites(case), ACTIONABLE_KINDS)


def rendered(row: dict[str, Any]) -> str:
    """A site in docs/BENCHMARK.md's `file:line:symbol:auto|manual` form."""
    return f"{row['path']}:{row['line']}:{row['symbol']}:{row['label']}"


def ground_truth_key(case: dict[str, Any]) -> tuple[str, ...]:
    """`pattern_key` from the reviewer's sites, not the scan's."""
    return tuple(sorted({row["symbol"] for row in sites(case) if row["kind"] in ACTIONABLE_KINDS}))


def verifiable(case: dict[str, Any]) -> bool:
    return bool(case["test_cmd"])


def accuracy(corpus: Corpus, case: dict[str, Any]) -> Any:
    from gate1_score import compare, rows

    found = corpus.findings.get(case["full_name"], [])
    return compare(labelled(case), rows(found, ACTIONABLE_KINDS))


def controls(corpus: Corpus) -> list[dict[str, Any]]:
    return list(corpus.cases["controls"])


def cases(corpus: Corpus) -> list[dict[str, Any]]:
    return list(corpus.cases["cases"])


def _rule_table(corpus: Corpus) -> list[str]:
    rows_ = cases(corpus)
    owners = Counter(corpus.repositories[case["full_name"]]["owner"] for case in rows_)
    holdout = [case for case in rows_ if case["split"] == "holdout"]
    shapes = {entry["control"] for entry in controls(corpus)}
    checks = [
        (
            "Every case pins both SDK versions exactly",
            all(
                EXACT_VERSION.match(case["from_version"])
                and EXACT_VERSION.match(case["to_version"])
                for case in rows_
            ),
        ),
        (
            "Every case names a full uv interpreter key",
            all(INTERPRETER_KEY.match(case["python"]) for case in rows_),
        ),
        (
            "Every case carries a split, and at least a third are holdout",
            all(case["split"] in SPLITS for case in rows_) and len(holdout) * 3 >= len(rows_),
        ),
        (
            "Every case carries hand-written ground truth, a reviewer and a date",
            all(sites(case) and case["reviewer"] and case["reviewed_at"] for case in rows_),
        ),
        (
            "Every case's `pattern_key` is the one its ground truth names",
            all(tuple(case["pattern_key"]) == ground_truth_key(case) for case in rows_),
        ),
        ("At most 2 cases share an owner", max(owners.values()) <= candidates.MAX_PER_OWNER),
        (f"At least {CASE_COUNT} cases", len(rows_) >= CASE_COUNT),
        (
            "The negative controls exist, including both Vertex origins",
            {"vertex-generative-models", "vertex-preview"} <= shapes,
        ),
    ]
    lines = ["| Rule | Holds |", "|---|---|"]
    for rule, holds in checks:
        lines.append(f"| {rule} | {'yes' if holds else 'NO'} |")
    return lines


def _case_table(corpus: Corpus) -> list[str]:
    lines = [
        "| # | Case | Split | SPDX | Interpreter | Sites | `auto` | `manual` | Key "
        "| Test command |",
        "|---:|---|---|---|---|---:|---:|---:|---:|---|",
    ]
    for index, case in enumerate(cases(corpus), start=1):
        rows_ = sites(case)
        auto = sum(1 for row in rows_ if row["label"] == "auto")
        repository = corpus.repositories[case["full_name"]]
        short = case["python"].removeprefix("cpython-").removesuffix("-macos-aarch64-none")
        lines.append(
            f"| {index} | [{case['full_name']}]({case['repo']}) | `{case['split']}` | "
            f"`{repository['license']}` | `{short}` | "
            f"{len(rows_)} | {auto} | {len(rows_) - auto} | {len(case['pattern_key'])} | "
            f"{'`' + case['test_cmd'] + '`' if case['test_cmd'] else '--'} |"
        )
    return lines


def _agreement_table(corpus: Corpus) -> list[str]:
    from gate1_score import _percent, rows

    lines = [
        "| Case | Key | Scan | Matched | Missed | Unexpected |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    total_key = total_found = total_hit = 0
    for case in cases(corpus):
        found = rows(corpus.findings.get(case["full_name"], []), ACTIONABLE_KINDS)
        key = labelled(case)
        score = accuracy(corpus, case)
        total_key += sum(key.values())
        total_found += sum(found.values())
        total_hit += score.true_positive
        lines.append(
            f"| `{case['id']}` | {sum(key.values())} | {sum(found.values())} | "
            f"{score.true_positive} | {score.missed} | {score.false_positive} |"
        )
    precision = None if total_found == 0 else total_hit / total_found
    recall = None if total_key == 0 else total_hit / total_key
    lines.append(
        f"| **all {len(cases(corpus))}** | **{total_key}** | **{total_found}** | "
        f"**{total_hit}** | **{total_key - total_hit}** | **{total_found - total_hit}** |"
    )
    lines.append("")
    lines.append(
        f"Precision **{_percent(precision)}**, recall **{_percent(recall)}**, over the four "
        "kinds that are a call site and matched on path, line, kind and symbol together."
    )
    return lines


def _change_table(corpus: Corpus) -> list[str]:
    """What each pack change meets in the ground truth, not in the scans."""
    lines = ["| Change | Cases | Call sites |", "|---|---:|---:|"]
    for surface in candidates.surfaces():
        names = set(surface.symbols)
        touched = [
            case for case in cases(corpus) if any(row["symbol"] in names for row in sites(case))
        ]
        total = sum(1 for case in cases(corpus) for row in sites(case) if row["symbol"] in names)
        lines.append(f"| `{surface.change}` | {len(touched)} | {total} |")
    return lines


def _control_table(corpus: Corpus) -> list[str]:
    lines = [
        "| Control | Shape | Repository | SPDX | Witness | Findings |",
        "|---|---|---|---|---|---:|",
    ]
    for entry in controls(corpus):
        found = corpus.findings.get(entry["full_name"], [])
        lines.append(
            f"| `{entry['control']}` | {entry['shape']} | "
            f"[{entry['full_name']}]({entry['repo']}) | `{entry['license']}` | "
            f"`{entry['witness']}` | {len(found)} |"
        )
    return lines


def _draw_table(corpus: Corpus) -> list[str]:
    lines = [
        "| Draw | Query | Hits | Examined | Outcome | Drawn | Why the rest were passed over |",
        "|---|---|---:|---:|---|---|---|",
    ]
    entries: list[tuple[str, dict[str, Any]]] = [("test suites", corpus.draws["test_suites"])]
    entries += [(entry["control"], entry) for entry in corpus.draws["controls"]]
    for label, entry in entries:
        reason = Counter(one["reason"] for one in entry["skipped"])
        tally = "; ".join(f"{count} {word}" for word, count in reason.most_common()) or "--"
        drawn = entry["drawn"]
        names = ", ".join(f"`{one}`" for one in drawn) if isinstance(drawn, list) else f"`{drawn}`"
        lines.append(
            f"| `{label}` | `{entry['query']}` | {entry['hits']} | {entry['examined']} | "
            f"`{entry['outcome']}` | {names if drawn else '--'} | {tally} |"
        )
    return lines


def render(corpus: Corpus) -> str:
    from gate1_score import _share

    rows_ = cases(corpus)
    data = corpus.cases
    runnable = [case for case in rows_ if verifiable(case)]
    holdout = [case for case in rows_ if case["split"] == "holdout"]
    total_sites = sum(len(sites(case)) for case in rows_)
    manual = sum(1 for case in rows_ for row in sites(case) if row["label"] == "manual")
    keys = {ground_truth_key(case) for case in rows_}
    disagree = [
        case
        for case in rows_
        if ground_truth_key(case)
        != candidates.pattern_key(corpus.findings.get(case["full_name"], []))
    ]
    covered = [case for case in rows_ if case["ground_truth"]["tests_cover_change"]]
    metrics_only = [
        case
        for case in rows_
        if corpus.repositories[case["full_name"]]["license"] not in PERMISSIVE
    ]
    lines = [
        f"{len(rows_)} cases and {len(controls(corpus))} negative controls, reviewed "
        f"{data['reviewed_at']} by {data['reviewer']}, over the corpus in "
        f"[`bench/CANDIDATES.md`](CANDIDATES.md) plus the two draws T27 made for itself. "
        f"Round {data['round']} installs `google-generativeai=={data['from_version']}` and "
        f"`google-genai=={data['to_version']}`, frozen for every case.",
        "",
        f"The ground truth is **{total_sites} hand-written call sites** over "
        f"{len(rows_)} repositories, written by reading the source at the pinned SHA. "
        f"{total_sites - manual} of them are `auto` -- a correct edit follows from the code "
        f"alone -- and {manual} are `manual`, each with its reason. "
        "Nothing here has been run: `bench/run.py` is T28's.",
        "",
        "**The rules, as applied.** Computed over the rows below, not asserted about them.",
        "",
        *_rule_table(corpus),
        "",
        "**The cases.** `Sites` counts ground-truth call sites, `Key` is the size of the "
        "case's `pattern_key`, and a case with no test command can never reach "
        "`verified_success`.",
        "",
        *_case_table(corpus),
        "",
        f"**The ceiling.** {len(runnable)} of {len(rows_)} cases carry a test command that "
        f"exercises the change without credentials, and {len(covered)} of those carry a "
        "reviewer's judgement that the tests cover it. `verified_success` needs a baseline "
        f"`pass` and an after `pass`, so at most **{_share(len(runnable), len(rows_))}** of "
        "this round can reach the only tier that counts toward the 70% target. That is the "
        "number Gate 4 has to be argued against.",
        "",
        f"**The split.** {len(rows_) - len(holdout)} `dev`, {len(holdout)} `holdout` "
        f"({_share(len(holdout), len(rows_))}), assigned by `sha256(owner)` inside two "
        "strata and never by hand.",
        "",
        f"**The second denominator.** The {len(rows_)} cases carry **{len(keys)} distinct "
        f"pattern keys** computed from the ground truth. On {len(disagree)} cases that key "
        "differs from the one computed from the scan, which is what a missed or an "
        "unexpected call site does to a denominator.",
        "",
        "**Publication.** "
        f"{len(rows_) - len(metrics_only)} of {len(rows_)} cases are under a permissive "
        "licence, so a `patch.diff` may be kept for them; "
        + (
            "every case may keep one."
            if not metrics_only
            else ", ".join(f"`{case['id']}`" for case in metrics_only) + " is metrics-only under "
            "[BENCHMARK.md](../docs/BENCHMARK.md#licensing-and-publication-rules)."
        ),
        "",
        "**Where the key and the scanner disagree.** The key was written from the source "
        "before the scan record was opened, so this table is a measurement and not a "
        "tautology. `Missed` is a ground-truth call site the scan does not report; "
        "`Unexpected` is a reported call site the key does not have.",
        "",
        *_agreement_table(corpus),
        "",
        "**What the pack's changes meet in the ground truth.** A change is met when a "
        "hand-written call site names one of the legacy symbols its own parameters state.",
        "",
        *_change_table(corpus),
        "",
        "**The negative controls.** Each must produce no call site and no dependency pin. "
        "`Findings` is what the shipped scanner actually reported at that SHA, and the "
        "witness is the line proving the checkout holds the shape it was drawn for.",
        "",
        *_control_table(corpus),
        "",
        "**The two draws T27 made.** Dated, verbatim, with the count GitHub returned. Both "
        "follow the same corpus rules, and neither is appended to a corpus drawn on another day.",
        "",
        *_draw_table(corpus),
    ]
    return "\n".join(lines)


def block(text: str) -> str:
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no cases block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="exit 1 if the document is stale")
    arguments = parser.parse_args(argv)
    fresh = render(load())
    if not arguments.check:
        print(fresh)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) != fresh:
        print(f"{DOCUMENT.name} is stale; re-run `python bench/cases.py` and paste the block")
        return 1
    print(f"{DOCUMENT.name} is up to date with {DATA.name}")
    return 0


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    sys.exit(main())
