"""Compare the two arms over the development split, from records and a review.

Offline join of `bench/results/comparison/round-<n>.json`, `bench/cases.yaml` and the review in
`bench/comparison.yaml` into the block in `docs/BENCHMARK_RESULTS.md`. Both arms are scored by one
scan of the tree each left; obelize's scan count must equal the round's own arithmetic.

Usage::

    python bench/comparison.py           # print the block
    python bench/comparison.py --check   # fail when the document is stale
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any, NamedTuple

import run
import summarize
import yaml

ROOT = Path(__file__).resolve().parent.parent
DOCUMENT = ROOT / "docs" / "BENCHMARK_RESULTS.md"
RECORDS = ROOT / "bench" / "results" / "comparison"
DATA = ROOT / "bench" / "comparison.yaml"

MARKERS = (
    "<!-- comparison:begin -- generated by bench/comparison.py; edit that, not this -->",
    "<!-- comparison:end -->",
)

# Every table prints the arms in this order.
ARMS: tuple[str, ...] = ("obelize", "general_agent")

NAMES: dict[str, str] = {"obelize": "Obelize", "general_agent": "General agent"}

# Written out, not derived: a new finding kind fails a test instead of going uncounted.
# `text_mention` is the scanner's word for the key's `dynamic`.
ROW_KINDS: tuple[str, ...] = (
    "import",
    "call",
    "method_call",
    "attribute",
    "dynamic",
    "text_mention",
    "manifest",
    "star_import",
)

# Kinds that count as introduced legacy; a prose mention of the old distribution does not.
USAGE_KINDS: tuple[str, ...] = ("import", "call", "method_call", "attribute", "manifest")


class Cell(NamedTuple):
    """A legacy usage by file and symbol only: an edit moves lines.

    Kind is deliberately absent: the key's `dynamic` is the scanner's `text_mention`.
    """

    path: str
    symbol: str


class Comparison(NamedTuple):
    """`published` is the round's own result file per case id."""

    number: int
    cases: list[run.Case]
    record: dict[str, Any]
    review: dict[str, Any]
    published: dict[str, dict[str, Any]]


def load(number: int | None = None) -> Comparison:
    state = summarize.load()
    round_number = number if number is not None else state.number
    path = RECORDS / f"round-{round_number}.json"
    record = json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {"cases": {}}
    published = {
        json.loads(result.read_text(encoding="utf-8"))["case"]: json.loads(
            result.read_text(encoding="utf-8")
        )
        for result in sorted((run.RESULTS / f"round-{round_number}").glob("*.json"))
    }
    return Comparison(
        round_number,
        state.cases,
        record,
        yaml.safe_load(DATA.read_text(encoding="utf-8")),
        published,
    )


def dev(state: Comparison) -> list[run.Case]:
    """Dev-split cases the record holds, in case-file order."""
    return [
        case
        for case in state.cases
        if case.split == "dev" and case.id in state.record.get("cases", {})
    ]


def key_cells(case: run.Case) -> Counter[Cell]:
    """Key rows (call sites and pins) as a multiset of cells."""
    return Counter(
        Cell(str(row["path"]), str(row["symbol"]))
        for row in [
            *(case.ground_truth.get("call_sites") or ()),
            *(case.ground_truth.get("manifests") or ()),
        ]
    )


def scan_cells(rows: list[list[Any]], kinds: tuple[str, ...] = ROW_KINDS) -> Counter[Cell]:
    """One tree's scan rows as cells, keeping only `kinds`."""
    return Counter(
        Cell(str(path), str(symbol)) for path, _line, kind, symbol in rows if kind in kinds
    )


def trees(
    state: Comparison, case: run.Case, kinds: tuple[str, ...] = ROW_KINDS
) -> dict[str, Counter[Cell]]:
    """One case's scans, keyed `base` and one per arm."""
    per_case = state.record["cases"][case.id]["findings"]
    return {name: scan_cells(rows, kinds) for name, rows in per_case.items()}


def visible(state: Comparison, case: run.Case) -> Counter[Cell]:
    """Key rows the scanner reports on the untouched tree; the rest are credited to no arm."""
    base = trees(state, case)["base"]
    wanted = key_cells(case)
    return Counter({cell: min(count, base[cell]) for cell, count in wanted.items() if base[cell]})


def cleared(state: Comparison, case: run.Case, arm: str) -> Counter[Cell]:
    """Visible key rows gone from the arm's tree, capped by visibility.

    A deleted key file clears its rows too; the record's `missing_key_files` names it.
    """
    scans = trees(state, case)
    return clearance(scans["base"], visible(state, case), scans[arm])


def clearance(base: Counter[Cell], seen: Counter[Cell], after: Counter[Cell]) -> Counter[Cell]:
    """The `cleared` arithmetic, shared with the repeat run so there is one formula."""
    return Counter(
        {
            cell: min(count, base[cell] - after[cell])
            for cell, count in seen.items()
            if base[cell] > after[cell]
        }
    )


def introduced(state: Comparison, case: run.Case, arm: str) -> int:
    """Legacy usages in the arm's tree that its starting tree did not have."""
    scans = trees(state, case, USAGE_KINDS)
    base, after = scans["base"], scans[arm]
    return sum(max(0, count - base[cell]) for cell, count in after.items())


def changes(state: Comparison, case: run.Case, arm: str) -> list[dict[str, Any]]:
    field = "changes" if arm == "general_agent" else "obelize_changes"
    changed: list[dict[str, Any]] = state.record["cases"][case.id][field]
    return changed


def off_key(state: Comparison, case: run.Case, arm: str) -> list[str]:
    """Files the arm changed with no key row: a pointer for the review, not a verdict."""
    named = {path for path, _, _ in run.expected_rows(case)}
    return sorted(
        str(change["path"])
        for change in changes(state, case, arm)
        if str(change["path"]) not in named
    )


def rows(case: run.Case) -> int:
    """Key rows in this case, call sites and pins together."""
    return len(run.expected_rows(case))


def published_migrated(state: Comparison, case: run.Case) -> int:
    """Obelize's migrated rows by the round's plan arithmetic, not a scan.

    The calibration test asserts this equals the scan's count; that licenses scoring the agent.
    """
    measured = state.published[case.id]["measurements"]
    return rows(case) - int(measured["unmigrated"])


def review(state: Comparison, case: run.Case, arm: str) -> dict[str, Any]:
    """The reviewer's entry for one arm on one case; a missing entry is refused."""
    entry = ((state.review.get("reviews") or {}).get(arm) or {}).get(case.id)
    if entry is None:
        raise SystemExit(f"bench/comparison.yaml has no {arm} review of {case.id}")
    return dict(entry)


def wrong_edits(state: Comparison, case: run.Case, arm: str) -> list[dict[str, Any]]:
    """Edits the arm wrote that a reviewer would undo or repair: the only hand-judged input."""
    return list(review(state, case, arm).get("wrong") or ())


def left(state: Comparison, case: run.Case, arm: str) -> int:
    """Key rows still legacy after the arm, including rows the scanner never saw."""
    return rows(case) - sum(cleared(state, case, arm).values())


def human_edits(state: Comparison, case: run.Case, arm: str) -> int:
    """Rows left plus rejected edits; rows, not `bench/run.py`'s hunks (ADR-045 D4)."""
    return left(state, case, arm) + len(wrong_edits(state, case, arm))


def patch_correct(state: Comparison, case: run.Case, arm: str) -> bool | None:
    """Derived from the review; `None` when no file changed, as `False` would claim a read."""
    if not changes(state, case, arm):
        return None
    return not wrong_edits(state, case, arm)


def suite(state: Comparison, case: run.Case, arm: str) -> dict[str, Any]:
    """The arm's after-phase suite, in `obelize verify`'s four statuses."""
    if arm == "obelize":
        published: dict[str, Any] = state.published[case.id]["measurements"]["tests_after"]
        return published
    after = state.record["cases"][case.id]["tests_after"]
    return after or {"status": "not_run", "passed": None, "failed": None, "skipped": None}


def baseline(state: Comparison, case: run.Case) -> dict[str, Any]:
    """The suite before either arm: measured once by the round, on the bytes both arms got."""
    published: dict[str, Any] = state.published[case.id]["measurements"]["tests_baseline"]
    return published


def compiles(state: Comparison, case: run.Case, arm: str) -> bool | None:
    """Whether every Python file the arm wrote still compiles."""
    if arm == "obelize":
        published: bool | None = state.published[case.id]["measurements"]["patch_compiles"]
        return published
    checked: bool | None = state.record["cases"][case.id]["compiles"]
    return checked


def runtime(state: Comparison, case: run.Case, arm: str) -> float:
    """Seconds for one pass: the round's `obelize fix --apply`, or the agent's own two stamps.

    Neither includes fetching, building a venv or running a suite.
    """
    if arm == "obelize":
        published: float = state.published[case.id]["measurements"]["runtime_seconds"]
        return published
    return float(state.record["cases"][case.id]["runtime_seconds"])


def tier(state: Comparison, case: run.Case, arm: str) -> str:
    """`bench/run.py`'s ladder minus `false_positive` and `missed_call_site`, which need findings.

    Returns the round's published tier for every obelize dev case (tested). `_is_verified`'s
    `human_edits == 0` is deliberately absent: the `wrong` and `partial` returns force it to 0.
    """
    regressed = (
        bool(changes(state, case, arm))
        and baseline(state, case)["status"] == "pass"
        and suite(state, case, arm)["status"] == "fail"
    )
    if (
        compiles(state, case, arm) is False
        or patch_correct(state, case, arm) is False
        or introduced(state, case, arm) > 0
        or regressed
    ):
        return "wrong"
    if not changes(state, case, arm):
        return "unsupported"
    if left(state, case, arm) > 0:
        return "partial"
    after = suite(state, case, arm)
    verified = (
        after["status"] == "pass"
        and (after["passed"] is None or after["passed"] > 0)
        and bool(case.ground_truth.get("tests_cover_change"))
    )
    return "verified_success" if verified else "patched_unverified"


def divergence(state: Comparison, case: run.Case) -> dict[str, Any] | None:
    """A second agent run on the same bytes against the first: files, line counts, rows cleared."""
    again = state.record["cases"][case.id].get("repeat")
    if again is None:
        return None
    before = {str(change["path"]) for change in changes(state, case, "general_agent")}
    after = {str(change["path"]) for change in again["changes"]}
    shape = {
        (str(change["path"]), change["added"], change["removed"])
        for change in changes(state, case, "general_agent")
    }
    shape_again = {
        (str(change["path"]), change["added"], change["removed"]) for change in again["changes"]
    }
    scans = trees(state, case)
    seen = visible(state, case)
    return {
        "files": len(before | after),
        "same_files": before == after,
        "same_shape": shape == shape_again,
        "cleared": sum(clearance(scans["base"], seen, scans["general_agent"]).values()),
        "cleared_again": sum(
            clearance(scans["base"], seen, scan_cells(again["findings"])).values()
        ),
        "runtime": float(state.record["cases"][case.id]["runtime_seconds"]),
        "runtime_again": float(again["runtime_seconds"]),
    }


def counts(state: Comparison, case: run.Case, arm: str) -> dict[str, Any]:
    """Every published number for one arm on one case."""
    return {
        "rows": rows(case),
        "visible": sum(visible(state, case).values()),
        "cleared": sum(cleared(state, case, arm).values()),
        "left": left(state, case, arm),
        "introduced": introduced(state, case, arm),
        "off_key": len(off_key(state, case, arm)),
        "files": len(changes(state, case, arm)),
        "wrong": len(wrong_edits(state, case, arm)),
        "human_edits": human_edits(state, case, arm),
        "runtime": runtime(state, case, arm),
        "tier": tier(state, case, arm),
    }


def totals(state: Comparison, arm: str) -> dict[str, Any]:
    """`counts` summed over the development split."""
    per_case = [counts(state, case, arm) for case in dev(state)]
    added: dict[str, Any] = {
        field: sum(int(case[field]) for case in per_case)
        for field in ("rows", "visible", "cleared", "left", "introduced", "off_key", "wrong")
    }
    added["human_edits"] = sum(int(case["human_edits"]) for case in per_case)
    added["runtime"] = round(sum(float(case["runtime"]) for case in per_case), 1)
    added["cases"] = len(per_case)
    for name in run.TIERS:
        added[name] = sum(1 for case in per_case if case["tier"] == name)
    return added


def _arms_table(state: Comparison) -> list[str]:
    lines = [
        "| Arm | Cases | `verified_success` | Key rows | Rows migrated | Corrections left | "
        "Runtime |",
        "|---|---:|---:|---:|---:|---:|---:|",
    ]
    for arm in ARMS:
        added = totals(state, arm)
        lines.append(
            f"| {NAMES[arm]} | {added['cases']} | {added['verified_success']} | "
            f"{added['rows']} | {added['cleared']} ({_share(added['cleared'], added['rows'])}) | "
            f"{added['human_edits']} | {_seconds(added['runtime'])} |"
        )
    return lines


def _case_table(state: Comparison) -> list[str]:
    lines = [
        "| Case id | Key rows | Seen | Arm | Cleared | Left | Corrections | Files | Off key | "
        "Runtime | Tier |",
        "|---|---:|---:|---|---:|---:|---:|---:|---:|---:|---|",
    ]
    for case in dev(state):
        for index, arm in enumerate(ARMS):
            measured = counts(state, case, arm)
            head = (
                f"| `{case.id}` | {measured['rows']} | {measured['visible']} "
                if index == 0
                else "| | | "
            )
            lines.append(
                f"{head}| {NAMES[arm]} | {measured['cleared']} | {measured['left']} | "
                f"{measured['human_edits']} | {measured['files']} | {measured['off_key']} | "
                f"{_seconds(measured['runtime'])} | `{measured['tier']}` |"
            )
    for arm in ARMS:
        added = totals(state, arm)
        lines.append(
            f"| **Total** | {'**' + str(added['rows']) + '**' if arm == ARMS[0] else ''} | "
            f"{'**' + str(added['visible']) + '**' if arm == ARMS[0] else ''} | {NAMES[arm]} | "
            f"**{added['cleared']}** | **{added['left']}** | **{added['human_edits']}** | | "
            f"**{added['off_key']}** | **{_seconds(added['runtime'])}** | |"
        )
    return lines


def _tier_table(state: Comparison) -> list[str]:
    lines = ["| Tier | " + " | ".join(NAMES[arm] for arm in ARMS) + " |", "|---|---:|---:|"]
    counted = {arm: totals(state, arm) for arm in ARMS}
    for name in run.TIERS:
        lines.append(f"| `{name}` | " + " | ".join(str(counted[arm][name]) for arm in ARMS) + " |")
    return lines


def _off_key_table(state: Comparison) -> list[str]:
    lines = [
        "| Case id | Arm | Files off the key | New legacy usage | Edits the review rejected |",
        "|---|---|---|---:|---:|",
    ]
    for case in dev(state):
        for arm in ARMS:
            paths = off_key(state, case, arm)
            added = introduced(state, case, arm)
            rejected = len(wrong_edits(state, case, arm))
            if not paths and not added and not rejected:
                continue
            listed = ", ".join(f"`{path}`" for path in paths) or "--"
            lines.append(f"| `{case.id}` | {NAMES[arm]} | {listed} | {added} | {rejected} |")
    if len(lines) == 2:
        lines.append("| -- | | Neither arm wrote outside the key. | 0 | 0 |")
    return lines


def _repeat_table(state: Comparison) -> list[str]:
    lines = [
        "| Case id | Files touched | Same files | Same line counts | Cleared, run 1 / run 2 | "
        "Runtime, run 1 / run 2 |",
        "|---|---:|---|---|---|---|",
    ]
    for case in dev(state):
        again = divergence(state, case)
        if again is None:
            continue
        lines.append(
            f"| `{case.id}` | {again['files']} | {_yes(again['same_files'])} | "
            f"{_yes(again['same_shape'])} | {again['cleared']} / {again['cleared_again']} | "
            f"{_seconds(again['runtime'])} / {_seconds(again['runtime_again'])} |"
        )
    if len(lines) == 2:
        lines.append("| -- | | | | | No case was run twice. |")
    return lines


def _yes(value: bool) -> str:
    return "yes" if value else "**no**"


def _seconds(value: float) -> str:
    return f"{value:.1f}s" if value < 60 else f"{value / 60:.1f}m"


def _share(numerator: int, denominator: int) -> str:
    return f"{numerator / denominator * 100:.1f}%" if denominator else "--"


def render(state: Comparison) -> str:
    if not dev(state):
        return f"_Not run: round {state.number} has no collected comparison record._"
    guide = state.record["guide"]
    out = [
        f"Round {state.number}, development split, from `bench/cases.yaml`, "
        f"`bench/results/comparison/round-{state.number}.json`, "
        f"`bench/results/round-{state.number}/` and `bench/comparison.yaml`. "
        f"The other arm is a general-purpose coding agent given "
        f"[the migration guide]({guide['url']}) -- snapshotted {guide['fetched_at']}, "
        f"sha256 `{guide['sha256_text'][:12]}` -- and "
        "[one fixed prompt](../bench/COMPARISON_PROMPT.md), and nothing else.",
        "",
        "**Both arms, the same cases.** *Rows migrated* is a key row whose legacy usage "
        "a scan of the tree afterwards no longer reports; *corrections left* is every key "
        "row still legacy plus every edit the review rejected.",
        "",
    ]
    out += _arms_table(state)
    out += [
        "",
        "**The tiers.** The same ladder for both arms, which is the round's own minus the "
        "two rungs that read a findings document -- an agent publishes none. Over this "
        "split the ladder returns the tier the round published for every obelize case.",
        "",
    ]
    out += _tier_table(state)
    out += [
        "",
        "**Per case.** *Seen* is the key rows the scanner reports on the untouched tree; "
        "the rows it does not see are credited to neither arm and are in *left* for both. "
        "*Off key* is files an arm changed that the key names no row in, which is a "
        "pointer for the review and not a verdict.",
        "",
    ]
    out += _case_table(state)
    out += ["", "**Where an arm went outside the key**, and what the review made of it.", ""]
    out += _off_key_table(state)
    out += [
        "",
        "**Run it twice.** Obelize's answer is byte-identical output, asserted since "
        "Phase 1. This is the other arm's, measured over the same starting bytes.",
        "",
    ]
    out += _repeat_table(state)
    return "\n".join(out)


def block(text: str) -> str:
    """The document's text between the markers."""
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no comparison block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Compare the two arms over the dev split.")
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    arguments = parser.parse_args(argv)
    generated = render(load())
    if not arguments.check:
        print(generated)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) == generated:
        print(f"{DOCUMENT.name} is up to date with bench/comparison.yaml")
        return 0
    print(f"{DOCUMENT.name} is stale; run `python bench/comparison.py` and paste the block")
    return 1


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    raise SystemExit(main())
