"""Render the error-analysis block of `BENCHMARK_RESULTS.md`: why each key row did not migrate.

Joins `bench/cases.yaml`, `bench/results/errors/round-<n>.json` (from `bench/errors_collect.py`)
and the hand-written `bench/errors.yaml`. `lever()` replays the round with one cause fixed under
ADR-010's atomicity rules; lifting nothing reproduces the published migrated count.

Usage::

    python bench/errors.py            # print the block
    python bench/errors.py --check    # exit 1 if the document is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, NamedTuple

import run
import summarize
import yaml
from gate1_score import ACTIONABLE_KINDS
from gate1_score import Row as ScanRow
from gate1_score import rows as scan_rows

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "bench" / "errors.yaml"
RECORDS = ROOT / "bench" / "results" / "errors"
DOCUMENT = ROOT / "docs" / "BENCHMARK_RESULTS.md"

MARKERS = (
    "<!-- errors:begin -- generated by bench/errors.py; edit that, not this -->",
    "<!-- errors:end -->",
)

# Atomicity bails: consequences of another row's bail, kept apart from primary causes.
DERIVED_BAILS: tuple[str, ...] = ("file_not_fully_migrated", "repo_not_fully_migrated")

# `withheld`: the row's own bail; `derived`: a `DERIVED_BAILS` code; `missed`: never delivered.
STATES: tuple[str, ...] = ("migrated", "withheld", "derived", "missed")

# The three unmigrated states, plus `unexpected`: a reported row no key claims.
CAUSE_CLASSES: tuple[str, ...] = ("withheld", "derived", "missed", "unexpected")

# Closed: every cause becomes one of these, with no fourth option to escape into.
DISPOSITIONS: tuple[str, ...] = ("rule_change", "scan_change", "limitation")


class Row(NamedTuple):
    """One key row and what the round did with it."""

    case: str
    path: str
    line: int
    symbol: str
    state: str
    cause: str | None


class Analysis(NamedTuple):
    number: int
    cases: list[run.Case]
    record: dict[str, Any]
    key: dict[str, Any]


def load(number: int | None = None) -> Analysis:
    """The round `bench/cases.yaml` declares, plus everything written about it."""
    state = summarize.load()
    round_number = number if number is not None else state.number
    path = RECORDS / f"round-{round_number}.json"
    record = json.loads(path.read_text(encoding="utf-8")) if path.is_file() else {"cases": {}}
    return Analysis(round_number, state.cases, record, yaml.safe_load(DATA.read_text("utf-8")))


def graded(state: Analysis) -> list[run.Case]:
    """Every case but the negative controls."""
    return [case for case in state.cases if not case.control]


def miss_causes(state: Analysis) -> dict[tuple[str, str, int, str], str]:
    """The hand-written cause for every row the scan did not deliver."""
    return {
        (str(row["case"]), str(row["path"]), int(row["line"]), str(row["symbol"])): str(
            row["cause"]
        )
        for row in state.key.get("misses") or ()
    }


def rows(state: Analysis) -> list[Row]:
    """Every key row and its state, classified as `bench/run.py`'s `unmigrated()` does."""
    misses = miss_causes(state)
    found: list[Row] = []
    for case in graded(state):
        per_case = state.record["cases"].get(case.id)
        if per_case is None:
            continue
        withheld = {
            (str(row["path"]), int(row["line"]), str(row["symbol"] or "")): str(row["bail"])
            for row in per_case["withheld"]
        }
        landed = {(str(path), int(line)) for path, line in per_case["applied"]}
        for path, line, symbol in run.expected_rows(case):
            bail = withheld.get((path, line, symbol))
            if bail is not None:
                state_name = "derived" if bail in DERIVED_BAILS else "withheld"
                found.append(Row(case.id, path, line, symbol, state_name, bail))
            elif (path, line) in landed:
                found.append(Row(case.id, path, line, symbol, "migrated", None))
            else:
                cause = misses.get((case.id, path, line, symbol))
                found.append(Row(case.id, path, line, symbol, "missed", cause))
    return found


def observed(state: Analysis) -> Counter[str]:
    """Every cause the round holds, with its row count."""
    return Counter(row.cause for row in rows(state) if row.cause is not None)


def blockers(state: Analysis, case: run.Case) -> dict[str, set[str]]:
    """Per file, its own non-derived bails, read from withheld rows (`caused_by` is partial)."""
    per_case = state.record["cases"].get(case.id) or {"withheld": []}
    found: dict[str, set[str]] = {}
    for row in per_case["withheld"]:
        if str(row["bail"]) not in DERIVED_BAILS:
            found.setdefault(str(row["path"]), set()).add(str(row["bail"]))
    return found


def migrated(state: Analysis, case: run.Case, lifted: frozenset[str]) -> int:
    """How many of this case's rows migrate once `lifted` stops withholding.

    A file migrates when all its bails are lifted; the legacy pin moves only when every file has.
    Written files are deliberately absent from `files`: only bailed rows, whose files are in
    `stops`, are looked up there.
    """
    per_case = state.record["cases"].get(case.id)
    if per_case is None:
        return 0
    stops = blockers(state, case)
    files = {path for path, bails in stops.items() if bails <= lifted}
    landed = {(str(path), int(line)) for path, line in per_case["applied"]}
    whole_repo = all(bails <= lifted for bails in stops.values())
    withheld = {
        (str(row["path"]), int(row["line"]), str(row["symbol"] or "")): str(row["bail"])
        for row in per_case["withheld"]
    }
    total = 0
    for path, line, symbol in run.expected_rows(case):
        bail = withheld.get((path, line, symbol))
        if bail is None:
            total += (path, line) in landed
        elif bail == "repo_not_fully_migrated":
            total += whole_repo
        elif bail == "file_not_fully_migrated":
            total += path in files
        else:
            total += bail in lifted and path in files
    return total


def lever(state: Analysis, cause: str) -> int:
    """Rows gained if only this cause were fixed; zero for a cause the scan never reported."""
    base = sum(migrated(state, case, frozenset()) for case in graded(state))
    lifted = frozenset({cause})
    return sum(migrated(state, case, lifted) for case in graded(state)) - base


def ceiling(state: Analysis) -> int:
    """Rows that would migrate if every bail the round raised were fixed."""
    every = frozenset(
        bail for case in graded(state) for bails in blockers(state, case).values() for bail in bails
    )
    return sum(migrated(state, case, every) for case in graded(state))


def disposition(state: Analysis, cause: str) -> dict[str, Any]:
    """The hand-written entry for a cause, or a refusal naming it."""
    entry = (state.key.get("causes") or {}).get(cause)
    if entry is None:
        raise SystemExit(f"bench/errors.yaml has no disposition for {cause!r}")
    return dict(entry)


def _state_table(state: Analysis) -> list[str]:
    counted = Counter(row.state for row in rows(state))
    total = sum(counted.values())
    lines = ["| What happened to the row | Rows | Share |", "|---|---:|---:|"]
    for name in STATES:
        lines.append(f"| `{name}` | {counted[name]} | {_share(counted[name], total)} |")
    lines.append(f"| **Total** | **{total}** | |")
    return lines


def _cause_table(state: Analysis) -> list[str]:
    """Every cause with its rows, lever and disposition; ties sort by name for stable output."""
    counted = observed(state)
    lines = [
        "| Cause | Class | Rows | Lever | Disposition | Recorded |",
        "|---|---|---:|---:|---|---|",
    ]
    for cause, count in sorted(counted.items(), key=lambda pair: (-pair[1], pair[0])):
        entry = disposition(state, cause)
        pull = lever(state, cause)
        lines.append(
            f"| `{cause}` | {entry['class']} | {count} | {pull:+d} | "
            f"`{entry['disposition']}` | {entry['recorded']} |"
        )
    lines.append(f"| **Total** | | **{sum(counted.values())}** | -- | | |")
    return lines


def _disposition_table(state: Analysis) -> list[str]:
    counted = observed(state)
    lines = ["| Disposition | Causes | Rows |", "|---|---:|---:|"]
    for name in DISPOSITIONS:
        chosen = [c for c in counted if disposition(state, c)["disposition"] == name]
        lines.append(f"| `{name}` | {len(chosen)} | {sum(counted[c] for c in chosen)} |")
    return lines


def _case_table(state: Analysis) -> list[str]:
    """Per case: what migrated, what could, and what no bail stands between."""
    lines = [
        "| Case id | Split | Key rows | Migrated | Reachable | Out of reach |",
        "|---|---|---:|---:|---:|---:|",
    ]
    totals: Counter[str] = Counter()
    for case in graded(state):
        if case.id not in state.record["cases"]:
            continue
        every = frozenset(bail for bails in blockers(state, case).values() for bail in bails)
        counts = {
            "rows": len(run.expected_rows(case)),
            "migrated": migrated(state, case, frozenset()),
            "reachable": migrated(state, case, every),
        }
        counts["stuck"] = counts["rows"] - counts["reachable"]
        totals.update(counts)
        lines.append(
            f"| `{case.id}` | {case.split} | {counts['rows']} | {counts['migrated']} | "
            f"{counts['reachable']} | {counts['stuck']} |"
        )
    lines.append(
        f"| **Total** | | **{totals['rows']}** | **{totals['migrated']}** | "
        f"**{totals['reachable']}** | **{totals['stuck']}** |"
    )
    return lines


def unexpected(state: Analysis) -> list[tuple[str, ScanRow]]:
    """Findings no key claims; recomputed, not read from `false_positive`, so the two must agree."""
    found: list[tuple[str, ScanRow]] = []
    for case in graded(state):
        per_case = state.record["cases"].get(case.id)
        if per_case is None:
            continue
        extra = scan_rows(per_case["findings"], ACTIONABLE_KINDS) - run.key_rows(case)
        found += [(case.id, row) for row in sorted(extra.elements())]
    return found


def unexpected_causes(state: Analysis) -> dict[str, str]:
    """The hand-written cause for every finding no key row claims."""
    return {str(where): str(cause) for where, cause in (state.key.get("unexpected") or {}).items()}


def _unexpected_table(state: Analysis) -> list[str]:
    causes = unexpected_causes(state)
    lines = [
        "| Case id | Where | Symbol | Cause | Disposition | Recorded |",
        "|---|---|---|---|---|---|",
    ]
    for case_id, row in unexpected(state):
        cause = causes[f"{case_id}:{row.path}:{row.line}"]
        entry = disposition(state, cause)
        lines.append(
            f"| `{case_id}` | `{row.path}:{row.line}` | `{row.symbol}` | `{cause}` | "
            f"`{entry['disposition']}` | {entry['recorded']} |"
        )
    return lines


def _share(numerator: int, denominator: int) -> str:
    return f"{numerator / denominator * 100:.1f}%" if denominator else "--"


def render(state: Analysis) -> str:
    if not state.record["cases"]:
        return f"_None: round {state.number} has no collected record._"
    out = [
        f"Round {state.number}, from `bench/cases.yaml`, "
        f"`bench/results/errors/round-{state.number}.json` and `bench/errors.yaml`.",
        "",
        "**Where the rows went.** Every row every answer key names, once. "
        "`derived` is one of the two atomicity codes and is a consequence of a row "
        "in the same file or repository, never a fact about itself; `missed` is a row "
        "the scan delivered nothing at, so it carries no bail code and its cause is "
        "hand-written.",
        "",
    ]
    out += _state_table(state)
    out += [
        "",
        "**Every cause, and what happens about it.** The lever is the number this "
        "table exists for: how many rows would migrate if this cause alone were fixed "
        "and nothing else were, under the same two atomicity rules the round ran with. "
        "Levers do not add up -- two causes in one file each buy nothing on their own -- "
        "so the column has no total.",
        "",
    ]
    out += _cause_table(state)
    out += ["", "**The three dispositions**, over the causes above.", ""]
    out += _disposition_table(state)
    out += [
        "",
        "**Per case.** *Reachable* is what would migrate with every bail this round "
        "raised lifted at once, which is an upper bound and not a plan; *out of reach* "
        "is the rest, and no rule change reaches it because no pass reported the row.",
        "",
    ]
    out += _case_table(state)
    unexpected_rows = _unexpected_table(state)
    if len(unexpected_rows) > 2:
        out += [
            "",
            "**What the scan reported that no key claims.** A false positive that is "
            "withheld is not a false-positive edit, and none of these was applied.",
            "",
        ]
        out += unexpected_rows
    return "\n".join(out)


def block(text: str) -> str:
    """The document's text between the markers."""
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no errors block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Analyse a benchmark round's failures.")
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    arguments = parser.parse_args(argv)
    generated = render(load())
    if not arguments.check:
        print(generated)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) == generated:
        print(f"{DOCUMENT.name} is up to date with bench/errors.yaml")
        return 0
    print(f"{DOCUMENT.name} is stale; run `python bench/errors.py` and paste the block")
    return 1


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    sys.exit(main())
