"""Score the gate-1 measurement, offline, from what was committed.

Gate 1's numbers (docs/PRODUCT.md) from the scan record and hand-written keys, as the
docs/BENCHMARK_RESULTS.md block. Its test binds the record to the pack's `spec_sha256`
(what a scan reads), not the file's sha256.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, NamedTuple

import yaml

ROOT = Path(__file__).resolve().parent.parent
SAMPLE = ROOT / "bench" / "gate1" / "sample.yaml"
LABELS = ROOT / "bench" / "gate1" / "labels"
SCAN = ROOT / "bench" / "results" / "gate1" / "scan.json"
DOCUMENT = ROOT / "docs" / "BENCHMARK_RESULTS.md"

MARKERS = (
    "<!-- gate1:begin -- generated by bench/gate1_score.py; edit that, not this -->",
    "<!-- gate1:end -->",
)

# Kinds precision and recall count; deliberate `text_mention` and `manifest` rows are tabled apart.
ACTIONABLE_KINDS: frozenset[str] = frozenset({"import", "call", "method_call", "attribute"})

# Written out, not derived, so a new kind fails a test.
OTHER_KINDS: frozenset[str] = frozenset(
    {"text_mention", "manifest", "dynamic", "star_import", "parse_error"}
)

# Mirrors `obelize.models.WITHHELD`, copied so a package change cannot silently re-grade.
WITHHELD_STATUSES: frozenset[str] = frozenset({"needs_review", "unsupported"})

# Gate 1's 30% unresolved trigger, as reasons (docs/BENCHMARK.md); in neither set: not a usage.
RESOLVED_REASONS: frozenset[str] = frozenset(
    {
        "direct_import_resolved",
        "alias_resolved",
        "from_import_resolved",
        "receiver_bound_same_scope",
        "receiver_bound_module_const",
        "receiver_bound_self_attr",
    }
)
UNRESOLVED_REASONS: frozenset[str] = frozenset(
    {
        "conditional_binding",
        "module_alias_rebound",
        "receiver_unresolved",
        "dynamic_access",
        "star_import",
        "star_import_candidate",
    }
)


class Row(NamedTuple):
    """One call site, as both the answer key and the scanner name it."""

    path: str
    line: int
    kind: str
    symbol: str


@dataclass(frozen=True)
class Accuracy:
    true_positive: int
    false_positive: int
    missed: int

    @property
    def precision(self) -> float | None:
        """`None` when the scanner reported nothing, which is not precision 1."""
        found = self.true_positive + self.false_positive
        return self.true_positive / found if found else None

    @property
    def recall(self) -> float | None:
        """`None` when the key is empty, which a labelled repository never is."""
        labelled = self.true_positive + self.missed
        return self.true_positive / labelled if labelled else None


def rows(findings: list[dict[str, Any]], kinds: frozenset[str]) -> Counter[Row]:
    """The findings of `kinds` as a multiset: two chained calls can share a whole row."""
    return Counter(
        Row(
            path=str(finding["path"]),
            line=int(finding["line"]),
            kind=str(finding["kind"]),
            symbol=str(finding.get("symbol") or ""),
        )
        for finding in findings
        if finding["kind"] in kinds
    )


def compare(labelled: Counter[Row], found: Counter[Row]) -> Accuracy:
    """Match whole rows; a wrong symbol (the CLI prints it) is a false positive and a miss."""
    hits = labelled & found
    true_positive = sum(hits.values())
    return Accuracy(
        true_positive=true_positive,
        false_positive=sum(found.values()) - true_positive,
        missed=sum(labelled.values()) - true_positive,
    )


def zero_bail_files(findings: list[dict[str, Any]]) -> list[str]:
    """Files with an actionable eligible finding and none withheld (one bail blocks the file)."""
    eligible: set[str] = set()
    withheld: set[str] = set()
    for finding in findings:
        path = str(finding["path"])
        if finding["scan_status"] in WITHHELD_STATUSES:
            withheld.add(path)
        elif finding["scan_status"] == "eligible" and finding["kind"] in ACTIONABLE_KINDS:
            eligible.add(path)
    return sorted(eligible - withheld)


def resolution(findings: list[dict[str, Any]]) -> tuple[int, int]:
    """`(resolved, unresolved)` over every finding that is a usage at all."""
    resolved = sum(1 for row in findings if row["confidence_reason"] in RESOLVED_REASONS)
    unresolved = sum(1 for row in findings if row["confidence_reason"] in UNRESOLVED_REASONS)
    return resolved, unresolved


def _percent(value: float | None) -> str:
    return "--" if value is None else f"{value * 100:.1f}%"


def _share(numerator: int, denominator: int) -> str:
    return "--" if denominator == 0 else f"{numerator / denominator * 100:.1f}%"


def load() -> tuple[dict[str, Any], dict[str, Any], list[dict[str, Any]]]:
    sample = yaml.safe_load(SAMPLE.read_text(encoding="utf-8"))
    scanned = json.loads(SCAN.read_text(encoding="utf-8"))
    labels = [
        yaml.safe_load(path.read_text(encoding="utf-8")) for path in sorted(LABELS.glob("*.yaml"))
    ]
    return sample, scanned, labels


def _accuracy_table(scanned: dict[str, Any], labels: list[dict[str, Any]]) -> list[str]:
    by_name = {record["full_name"]: record for record in scanned["scanned"]}
    lines = [
        "| Repository | Files read | Labelled | Found | TP | FP | Missed | Precision | Recall |",
        "|---|---:|---:|---:|---:|---:|---:|---:|---:|",
    ]
    total = Accuracy(0, 0, 0)
    for label in labels:
        record = by_name[label["repository"]]
        key = rows(label["call_sites"], ACTIONABLE_KINDS)
        found = rows(record["findings"], ACTIONABLE_KINDS)
        one = compare(key, found)
        total = Accuracy(
            total.true_positive + one.true_positive,
            total.false_positive + one.false_positive,
            total.missed + one.missed,
        )
        lines.append(
            f"| [`{label['repository']}`]({label['url']}) | {len(label['files_read'])} "
            f"| {sum(key.values())} | {sum(found.values())} | {one.true_positive} "
            f"| {one.false_positive} | {one.missed} | {_percent(one.precision)} "
            f"| {_percent(one.recall)} |"
        )
    lines.append(
        f"| **Total** | | {total.true_positive + total.missed} "
        f"| {total.true_positive + total.false_positive} | {total.true_positive} "
        f"| {total.false_positive} | {total.missed} | **{_percent(total.precision)}** "
        f"| **{_percent(total.recall)}** |"
    )
    return lines


def other_kinds(
    scanned: dict[str, Any], labels: list[dict[str, Any]]
) -> tuple[Counter[str], Counter[str], Counter[str]]:
    """`(reported, expected, unexpected)` per kind; the keys predate the scan, rows match whole."""
    by_name = {record["full_name"]: record for record in scanned["scanned"]}
    reported: Counter[str] = Counter()
    expected: Counter[str] = Counter()
    unexpected: Counter[str] = Counter()
    for label in labels:
        wanted = set(rows(label["expected_other"], OTHER_KINDS))
        for row in label["expected_other"]:
            expected[row["kind"]] += 1
        for finding in by_name[label["repository"]]["findings"]:
            if finding["kind"] not in OTHER_KINDS:
                continue
            reported[finding["kind"]] += 1
            if next(iter(rows([finding], OTHER_KINDS))) not in wanted:
                unexpected[finding["kind"]] += 1
    return reported, expected, unexpected


def violations(scanned: dict[str, Any], labels: list[dict[str, Any]]) -> list[str]:
    """Every `must_not_report` position the scan reported anyway."""
    by_name = {record["full_name"]: record for record in scanned["scanned"]}
    found = []
    for label in labels:
        positions = {(row["path"], row["line"]) for row in label["must_not_report"]}
        for finding in by_name[label["repository"]]["findings"]:
            if (finding["path"], finding["line"]) in positions:
                found.append(f"{label['repository']} {finding['path']}:{finding['line']}")
    return sorted(found)


def _other_kinds_table(scanned: dict[str, Any], labels: list[dict[str, Any]]) -> list[str]:
    reported, expected, unexpected = other_kinds(scanned, labels)
    lines = ["| Kind | Reported | Expected by the keys | Unexpected |", "|---|---:|---:|---:|"]
    for kind in sorted(set(reported) | set(expected)):
        lines.append(f"| `{kind}` | {reported[kind]} | {expected[kind]} | {unexpected[kind]} |")
    forbidden = sum(len(label["must_not_report"]) for label in labels)
    broken = violations(scanned, labels)
    lines.extend(
        [
            "",
            f"{forbidden} position(s) the keys forbid outright, "
            f"{len(broken)} of them reported"
            + (f": {', '.join(f'`{row}`' for row in broken)}." if broken else "."),
        ]
    )
    return lines


def _frame_table(sample: dict[str, Any], scanned: dict[str, Any]) -> list[str]:
    bands = {row["band"]: row for row in sample["bands"]}
    by_band: dict[str, list[dict[str, Any]]] = {band: [] for band in bands}
    for record in scanned["scanned"]:
        by_band[record["band"]].append(record)
    lines = [
        "| File-size band | Population | Scanned | Errored | With a zero-bail file | Share |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    ok_total = 0
    zero_total = 0
    for band, row in bands.items():
        records = by_band[band]
        errored = [record for record in records if "error" in record]
        ok = [record for record in records if "error" not in record]
        zero = [record for record in ok if zero_bail_files(record["findings"])]
        ok_total += len(ok)
        zero_total += len(zero)
        lines.append(
            f"| `{band}` | {row['population']:,} | {len(ok)} | {len(errored)} "
            f"| {len(zero)} | {_share(len(zero), len(ok))} |"
        )
    lines.append(
        f"| **Total** | {sample['population']:,} | **{ok_total}** "
        f"| {len(scanned['scanned']) - ok_total} | **{zero_total}** "
        f"| **{_share(zero_total, ok_total)}** |"
    )
    return lines


def outcomes(scanned: dict[str, Any]) -> tuple[int, int, int]:
    """`(clean, partial, none)`: nothing withheld; withheld beside a zero-bail file; neither."""
    clean = partial = none = 0
    for record in scanned["scanned"]:
        if "error" in record:
            continue
        withheld = any(
            finding["scan_status"] in WITHHELD_STATUSES for finding in record["findings"]
        )
        if not withheld:
            clean += 1
        elif zero_bail_files(record["findings"]):
            partial += 1
        else:
            none += 1
    return clean, partial, none


def _bail_table(scanned: dict[str, Any]) -> list[str]:
    """Bail codes by frequency; atomicity-derived ones are marked and not counted as primary."""
    derived = {"file_not_fully_migrated", "repo_not_fully_migrated"}
    counted: Counter[str] = Counter(
        finding["bail"]
        for record in scanned["scanned"]
        if "error" not in record
        for finding in record["findings"]
        if finding.get("bail")
    )
    lines = ["| Bail | Rows | |", "|---|---:|---|"]
    for code, rows_ in counted.most_common():
        mark = "derived from another row's bail" if code in derived else ""
        lines.append(f"| `{code}` | {rows_} | {mark} |")
    primary = sum(count for code, count in counted.items() if code not in derived)
    lines.append(f"| **Primary causes** | **{primary}** | |")
    return lines


def declarations(scanned: dict[str, Any]) -> Counter[str]:
    """Each declared Python floor with its count, for ADR-023 D6."""
    return Counter(
        record["runtime"]["declared"] or "(none declared)"
        for record in scanned["scanned"]
        if "error" not in record
    )


def _runtime_table(scanned: dict[str, Any]) -> list[str]:
    counted = declarations(scanned)
    reads = {
        record["runtime"]["declared"] or "(none declared)": record["runtime"]["blocked"]
        for record in scanned["scanned"]
        if "error" not in record
    }
    lines = ["| Declares | Repositories | Reads as |", "|---|---:|---|"]
    for spelling, count in sorted(counted.items(), key=lambda row: (-row[1], row[0])):
        verdict = "**blocked**" if reads[spelling] else "not blocked"
        lines.append(f"| `{spelling}` | {count} | {verdict} |")
    blocked = sum(1 for spelling, count in counted.items() if reads[spelling] for _ in range(count))
    lines.append(f"| **Blocked** | **{blocked}** | |")
    return lines


def _resolution_table(scanned: dict[str, Any]) -> list[str]:
    resolved = 0
    unresolved = 0
    for record in scanned["scanned"]:
        if "error" not in record:
            one, two = resolution(record["findings"])
            resolved += one
            unresolved += two
    total = resolved + unresolved
    return [
        "| Usages | Statically resolved | Unresolved | Unresolved share | Gate 1 trigger |",
        "|---:|---:|---:|---:|---|",
        f"| {total} | {resolved} | {unresolved} | {_share(unresolved, total)} "
        f"| {'fires' if total and unresolved / total > 0.30 else 'does not fire'} |",
    ]


def render(sample: dict[str, Any], scanned: dict[str, Any], labels: list[dict[str, Any]]) -> str:
    ok = [record for record in scanned["scanned"] if "error" not in record]
    findings = sum(len(record["findings"]) for record in ok)
    touched = sum(len({row["path"] for row in record["findings"]}) for record in ok)
    clean = sum(len(zero_bail_files(record["findings"])) for record in ok)
    selected = sum(record["counts"]["files_selected"] for record in ok)
    parsed = sum(record["counts"]["files_parsed"] for record in ok)
    lines = [
        f"Frame drawn {sample['queried_at']} over the term `{sample['term']}`; "
        f"{len(sample['repositories'])} repositories in the frame, {len(ok)} scanned, "
        f"{selected} file(s) selected and {parsed} parsed -- the byte prefilter eliminated "
        f"the rest -- for {findings} findings over {touched} file(s), {clean} of which "
        "nothing bails in.",
        "",
        f"Measured with obelize {scanned['obelize_version']} on CPython "
        f"{scanned['python']} / {scanned['machine']}, against pack "
        f"`{scanned['pack']}` sha256 `{scanned['pack_sha256'][:16]}...`. Nothing re-fetches "
        "eighty checkouts on CI, so these records are a dated artefact: a change to the "
        "scanner does not invalidate them visibly, and re-running "
        "`bench/gate1_collect.py scan` is what makes the number current again. A change to "
        "what the **pack** tells a scan to look for does fail a test -- the projection "
        f"`{scanned['spec_sha256'][:16]}...`, which is the whole of what `scan/` and "
        "`impact/` read, and not the pack's own bytes, which move whenever a rewrite rule "
        "gains a parameter.",
        "",
        "**Precision and recall, over the hand-labelled repositories.** Actionable kinds "
        f"only ({', '.join(f'`{kind}`' for kind in sorted(ACTIONABLE_KINDS))}); a row matches "
        "on path, line, kind and symbol together.",
        "",
        *_accuracy_table(scanned, labels),
        "",
        "**Everything else those repositories reported.** Excluded from the rate above; the "
        "keys predict these rows too, and the positions they forbid outright are counted "
        "under the table.",
        "",
        *_other_kinds_table(scanned, labels),
        "",
        "**Repositories with at least one file where nothing bails.** The number Phase 2's "
        "scope turns on: a file with an actionable eligible finding and no withheld finding.",
        "",
        *_frame_table(sample, scanned),
        "",
        f"Of the {sum(outcomes(scanned))} repositories scanned, {outcomes(scanned)[0]} had "
        f"nothing withheld anywhere, {outcomes(scanned)[1]} had a zero-bail file beside a "
        f"withheld one, and {outcomes(scanned)[2]} had no migratable file at all.",
        "",
        "**What withheld the rest.** The ranked reason a real file is not migratable, which "
        "is the table Phase 2's rule order is read from.",
        "",
        *_bail_table(scanned),
        "",
        "**What repositories declare about their Python.** `blocked: runtime_unsupported` "
        "is read from a manifest and never from `setup.py`, which is code; this is how "
        "often any of that fires outside a fixture.",
        "",
        *_runtime_table(scanned),
        "",
        "**Static resolution, over every usage in the frame.** Gate 1 narrows `scan` when "
        "more than 30% of usages cannot be resolved statically.",
        "",
        *_resolution_table(scanned),
    ]
    return "\n".join(lines)


def block(text: str) -> str:
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no gate1 block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Score the gate-1 measurement.")
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    arguments = parser.parse_args(argv)
    generated = render(*load())
    if not arguments.check:
        print(generated)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) == generated:
        print(f"{DOCUMENT.name} is up to date with bench/results/gate1/scan.json")
        return 0
    print(f"{DOCUMENT.name} is stale; run `python bench/gate1_score.py` and paste the block")
    return 1


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    sys.exit(main())
