"""Render the round block of `BENCHMARK_RESULTS.md` from `bench/run.py`'s result files.

Owns only that fence. The ceiling table needs only the keys, so it renders before the round runs.

Usage::

    python bench/summarize.py            # print the block
    python bench/summarize.py --check    # exit 1 if the document is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from pathlib import Path
from typing import Any, NamedTuple

import cases
import run

ROOT = Path(__file__).resolve().parent.parent
DOCUMENT = ROOT / "docs" / "BENCHMARK_RESULTS.md"

MARKERS = (
    "<!-- round:begin -- generated by bench/summarize.py; edit that, not this -->",
    "<!-- round:end -->",
)

# In the order the tables print them.
SPLITS: tuple[str, ...] = ("dev", "holdout")


class Round(NamedTuple):
    number: int
    cases: list[run.Case]
    results: dict[str, dict[str, Any]]


def load(results: Path | None = None) -> Round:
    """The round `bench/cases.yaml` declares, plus the results written for it."""
    number = int(cases.load().cases["round"])
    folder = results if results is not None else run.RESULTS / f"round-{number}"
    return Round(number, run.corpus(), _results(folder))


def _results(folder: Path) -> dict[str, dict[str, Any]]:
    """Result files keyed by case id; any other `schema_version` is refused, never mixed in."""
    if not folder.is_dir():
        return {}
    found: dict[str, dict[str, Any]] = {}
    for path in sorted(folder.glob("*.json")):
        record = json.loads(path.read_text(encoding="utf-8"))
        if record.get("schema_version") != run.RESULT_SCHEMA_VERSION:
            raise SystemExit(f"{path.name}: schema_version {record.get('schema_version')!r}")
        found[str(record["case"])] = record
    return found


def graded(state: Round) -> list[run.Case]:
    """The cases the headline is computed over: everything but the controls."""
    return [case for case in state.cases if not case.control]


def patterns(state: Round) -> dict[str, list[run.Case]]:
    """Graded cases grouped by pattern, so near-identical call sites count once."""
    groups: dict[str, list[run.Case]] = {}
    for case in graded(state):
        groups.setdefault(_pattern_key(case), []).append(case)
    return groups


def _pattern_key(case: run.Case) -> str:
    """The sorted legacy symbols the key names, as one comparable string."""
    rowset = [
        *(case.ground_truth.get("call_sites") or ()),
        *(case.ground_truth.get("manifests") or ()),
    ]
    return " ".join(sorted({str(row["symbol"]) for row in rowset}))


def tier_of(state: Round, case: run.Case) -> str | None:
    """The case's tier, or `None` if it has not run."""
    record = state.results.get(case.id)
    return str(record["tier"]) if record else None


def _ceiling_table(state: Round) -> list[str]:
    """Which cases can reach the headline at all, and what caps the rest."""
    reasons: Counter[str] = Counter()
    lines = [
        "| Case | Split | Can reach `verified_success` | What caps it |",
        "|---|---|---|---|",
    ]
    reachable = 0
    for case in graded(state):
        why = run.ceiling(case)
        reachable += why is None
        reasons[why or "nothing"] += 1
        lines.append(
            f"| `{case.id}` | {case.split} | {'yes' if why is None else 'no'} | {why or '--'} |"
        )
    lines.append(
        f"| **Total** | | **{reachable} of {len(graded(state))}** | "
        f"{'; '.join(f'{count} {reason}' for reason, count in sorted(reasons.items()))} |"
    )
    return lines


def _summary_table(state: Round) -> list[str]:
    split = Counter(case.split for case in graded(state))
    provenance = _provenance(state)
    return [
        "| Round | Cases (n) | dev / holdout | Unique patterns | Controls | Results on disk |",
        "|---:|---:|---|---:|---:|---|",
        f"| {state.number} | {len(graded(state))} | "
        f"{split['dev']} / {split['holdout']} | {len(patterns(state))} | "
        f"{len(state.cases) - len(graded(state))} | {provenance} |",
    ]


def _provenance(state: Round) -> str:
    """What the results were measured with, or that there are none."""
    if not state.results:
        return "none -- the round has not been run"
    versions = sorted({str(r["provenance"]["obelize_version"]) for r in state.results.values()})
    packs = sorted({str(r["provenance"]["pack_sha256"])[:16] for r in state.results.values()})
    return f"{len(state.results)}, obelize {', '.join(versions)}, pack `{', '.join(packs)}...`"


def _headline_table(state: Round) -> list[str]:
    """The rate, over cases and over unique patterns, each with its own `n`."""
    lines = ["| Scope | n | verified_success | Rate |", "|---|---:|---:|---:|"]
    if not state.results:
        return []
    over_cases = [case for case in graded(state) if tier_of(state, case) is not None]
    wins = sum(tier_of(state, case) == "verified_success" for case in over_cases)
    lines.append(f"| Cases | {len(over_cases)} | {wins} | {_share(wins, len(over_cases))} |")
    for side in SPLITS:
        subset = [case for case in over_cases if case.split == side]
        won = sum(tier_of(state, case) == "verified_success" for case in subset)
        lines.append(f"| Cases ({side}) | {len(subset)} | {won} | {_share(won, len(subset))} |")
    # `any`, not `all`: grouping stops inflation; it must not let one case veto another.
    for scope in (None, *SPLITS):
        groups = _run_patterns(state, scope)
        won = sum(
            any(tier_of(state, case) == "verified_success" for case in members)
            for members in groups.values()
        )
        label = "Unique patterns" if scope is None else f"Unique patterns ({scope})"
        lines.append(f"| {label} | {len(groups)} | {won} | {_share(won, len(groups))} |")
    return lines


def _run_patterns(state: Round, split: str | None) -> dict[str, list[run.Case]]:
    """Patterns with a result on one split or both; one can span both, so the rows need not sum."""
    groups: dict[str, list[run.Case]] = {}
    for key, members in patterns(state).items():
        inside = [
            case
            for case in members
            if tier_of(state, case) is not None and split in (None, case.split)
        ]
        if inside:
            groups[key] = inside
    return groups


def _tier_table(state: Round) -> list[str]:
    if not state.results:
        return []
    lines = ["| Tier | dev | holdout | Total |", "|---|---:|---:|---:|"]
    for name in run.TIERS:
        counts = [
            sum(1 for case in graded(state) if case.split == side and tier_of(state, case) == name)
            for side in SPLITS
        ]
        lines.append(f"| `{name}` | {counts[0]} | {counts[1]} | {sum(counts)} |")
    return lines


def _case_table(state: Round) -> list[str]:
    if not state.results:
        return []
    lines = [
        "| Case id | Split | Tier | Detected | FP | Missed | Unmigrated | Human edits |"
        " Runtime (s) |",
        "|---|---|---|---:|---:|---:|---:|---:|---:|",
    ]
    totals: Counter[str] = Counter()
    runtime = 0.0
    for case in graded(state):
        record = state.results.get(case.id)
        if record is None:
            continue
        measured = record["measurements"]
        for column in ("detected", "false_positive", "missed_call_site", "unmigrated"):
            totals[column] += int(measured[column])
        runtime += float(measured["runtime_seconds"])
        lines.append(
            f"| `{case.id}` | {case.split} | `{record['tier']}` | {measured['detected']} | "
            f"{measured['false_positive']} | {measured['missed_call_site']} | "
            f"{measured['unmigrated']} | {_number(measured['human_edits'])} | "
            f"{measured['runtime_seconds']} |"
        )
    lines.append(
        f"| **Total** | | | **{totals['detected']}** | **{totals['false_positive']}** | "
        f"**{totals['missed_call_site']}** | **{totals['unmigrated']}** | | "
        f"**{round(runtime, 1)}** |"
    )
    return lines


def _suite_table(state: Round) -> list[str]:
    """Each suite's counts on both sides of the swap: a `pass` can hide skipped tests."""
    lines = [
        "| Case id | Baseline | pass / fail / skip | After | pass / fail / skip |",
        "|---|---|---|---|---|",
    ]
    rows = 0
    for case in graded(state):
        record = state.results.get(case.id)
        if record is None or record["measurements"]["tests_baseline"]["status"] == "not_run":
            continue
        rows += 1
        before, after = (record["measurements"][k] for k in ("tests_baseline", "tests_after"))
        lines.append(
            f"| `{case.id}` | `{before['status']}` | {_counts(before)} | "
            f"`{after['status']}` | {_counts(after)} |"
        )
    return lines if rows else []


def _counts(phase: dict[str, Any]) -> str:
    """`pass / fail / skip`, or `--` without a junit report."""
    fields = [_number(phase.get(key)) for key in ("passed", "failed", "skipped")]
    return "--" if set(fields) == {"--"} else " / ".join(fields)


def _control_table(state: Round) -> list[str]:
    """The negative controls, excluded from every rate."""
    controls = [case for case in state.cases if case.control]
    lines = [
        "| Case id | Must produce | Tier | Findings | False-positive edits |",
        "|---|---|---|---:|---:|",
    ]
    for case in controls:
        record = state.results.get(case.id)
        if record is None:
            lines.append(f"| `{case.id}` | no call site and no pin | -- | -- | -- |")
            continue
        measured = record["measurements"]
        lines.append(
            f"| `{case.id}` | no call site and no pin | `{record['tier']}` | "
            f"{measured['detected']} | {measured['false_positive_edit']} |"
        )
    return lines


def _error_notes(state: Round) -> list[str]:
    errored = [
        (case_id, record["error"])
        for case_id, record in sorted(state.results.items())
        if record["error"] is not None
    ]
    if not errored:
        return []
    lines = ["| Case id | Step | Reason | Detail |", "|---|---|---|---|"]
    for case_id, error in errored:
        lines.append(
            f"| `{case_id}` | `{error['step']}` | `{error['reason']}` | {error['detail']} |"
        )
    return lines


def _number(value: Any) -> str:
    """A count, or `--` where nobody has answered yet."""
    return "--" if value is None else str(value)


def _share(numerator: int, denominator: int) -> str:
    return f"{numerator / denominator * 100:.1f}%" if denominator else "--"


def render(state: Round) -> str:
    out: list[str] = []
    out.append(
        f"Round {state.number}, from `bench/cases.yaml` and `bench/results/round-{state.number}/`."
    )
    out.append("")
    out += _summary_table(state)
    out.append("")
    out.append(
        "**What can reach the headline, computed from the keys before the round runs.** "
        "`verified_success` needs a baseline `pass`, an after `pass`, tests that cover the "
        "change and no hunk a human had to write, so every row the key names has to be one "
        "a rule can make. A case with a `manual` row is capped below the headline whatever "
        "the scanner does, and so is a case whose key names a line the pack flags rather "
        "than edits."
    )
    out.append("")
    out += _ceiling_table(state)
    out.append("")
    out.append(
        "**The rate.** Only `verified_success` counts toward it, and it is reported over "
        "cases and again over unique `pattern_key` values, each with its own `n`."
    )
    out.append("")
    out += _headline_table(state) or [_absent("no case has been run")]
    out.append("")
    out.append("**Outcome tiers.** Computed from the result files, never assigned by hand.")
    out.append("")
    out += _tier_table(state) or [_absent("no case has been run")]
    out.append("")
    out.append("**Every case in the round**, including the wrong, the errored and the unsupported.")
    out.append("")
    out += _case_table(state) or [_absent("no case has been run")]
    suites = _suite_table(state)
    if suites:
        out.append("")
        out.append(
            "**What the suites did.** A `pass` is not a suite that ran: the skip "
            "column is the difference, and `tests_cover_change` is still read from "
            "the key rather than from the run."
        )
        out.append("")
        out += suites
    out.append("")
    out.append(
        "**Negative controls.** They feed the false-positive table and are excluded from "
        "every rate above; an applied edit on one is a false positive by construction."
    )
    out.append("")
    out += _control_table(state)
    notes = _error_notes(state)
    if notes:
        out.append("")
        out.append("**What errored.** A crash or a timeout, with the step it happened at.")
        out.append("")
        out += notes
    return "\n".join(out)


def _absent(why: str) -> str:
    """The line that replaces an empty table."""
    return f"_None: {why}._"


def block(text: str) -> str:
    """The document's text between the markers."""
    begin, end = MARKERS
    if begin not in text or end not in text:
        raise SystemExit(f"{DOCUMENT.name} has no round block; add both markers first")
    return text.split(begin, 1)[1].split(end, 1)[0].strip("\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Summarise a benchmark round.")
    parser.add_argument("--check", action="store_true", help="fail when the document is stale")
    arguments = parser.parse_args(argv)
    generated = render(load())
    if not arguments.check:
        print(generated)
        return 0
    if block(DOCUMENT.read_text(encoding="utf-8")) == generated:
        print(f"{DOCUMENT.name} is up to date with bench/results/")
        return 0
    print(f"{DOCUMENT.name} is stale; run `python bench/summarize.py` and paste the block")
    return 1


if __name__ == "__main__":  # pragma: no cover - the module is imported by its test
    sys.exit(main())
