"""The encoding fixtures keep their exact bytes, and each `.after.py` key its input's shape.

They alone evidence `roundtrip_mismatch`, both `input_does_not_parse` gates and ADR-008's
bytes-in/bytes-out rule, and an editor, git filter or formatter would silently normalise them.
This runs the builder's `--check` comparison in the ordinary matrix.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path
from typing import Any

import pytest

ROOT = Path(__file__).resolve().parents[2]
ENCODING_DIR = ROOT / "tests" / "fixtures" / "scan" / "encoding"
BUILDER = ENCODING_DIR / "_build.py"


def _load_builder() -> Any:
    """Import `_build.py` by path: it is a fixture generator, not a package."""
    spec = importlib.util.spec_from_file_location("obelize_encoding_fixture_builder", BUILDER)
    assert spec is not None
    assert spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    # Bytecode left in a fixture directory would travel with every copy of it.
    writes, sys.dont_write_bytecode = sys.dont_write_bytecode, True
    try:
        spec.loader.exec_module(module)
    finally:
        sys.dont_write_bytecode = writes
    return module


builder = _load_builder()
GENERATED: dict[str, bytes] = builder.build()


def test_importing_the_builder_left_no_bytecode_beside_the_fixtures() -> None:
    assert not (ENCODING_DIR / "__pycache__").exists()


def test_the_generator_and_the_directory_agree_on_which_files_exist() -> None:
    on_disk = {p.name for p in ENCODING_DIR.glob("*.py")} - {"_build.py"}
    assert on_disk == set(GENERATED)


@pytest.mark.parametrize("name", sorted(GENERATED))
def test_fixture_bytes_are_exactly_what_the_generator_produces(name: str) -> None:
    on_disk = (ENCODING_DIR / name).read_bytes()
    expected = GENERATED[name]
    assert on_disk == expected, (
        f"{name} on disk differs from the generated bytes "
        f"({len(on_disk)} vs {len(expected)}). These files exist for their exact bytes; "
        f"regenerate with `uv run python {BUILDER.relative_to(ROOT)}` if the change "
        f"is intended, and update ground_truth.yaml in the same commit."
    )


@pytest.mark.parametrize("name", sorted(builder.EXPECTED))
def test_roundtrip_and_compile_match_the_recorded_ground_truth(name: str) -> None:
    import libcst as cst

    want_roundtrip, want_compiles, want_lost = builder.EXPECTED[name]
    data = (ENCODING_DIR / name).read_bytes()

    module = cst.parse_module(data)
    assert (module.bytes == data) is want_roundtrip
    if not want_roundtrip:
        assert len(data) - len(module.bytes) == want_lost

    if want_compiles:
        compile(data, name, "exec")
    else:
        with pytest.raises(SyntaxError) as excinfo:
            compile(data, name, "exec")
        assert excinfo.value.lineno == builder.PYTHON2_SYNTAX_ERROR_LINENO


def test_every_generated_file_is_graded_by_one_of_the_two_tables() -> None:
    """`EXPECTED` cannot describe a file libcst refuses; one in neither table is never graded."""
    assert set(builder.EXPECTED) | {builder.LIBCST_REFUSES} == set(GENERATED)
    assert builder.LIBCST_REFUSES not in builder.EXPECTED


def test_the_one_file_libcst_refuses_reports_the_recorded_coordinates() -> None:
    """Two traps: `except SyntaxError` misses `cst.ParserSyntaxError` and ends the run here,
    and its `.raw_*` and `.editor_*` coordinates differ by one column."""
    import libcst as cst

    assert not issubclass(cst.ParserSyntaxError, SyntaxError)

    data = (ENCODING_DIR / builder.LIBCST_REFUSES).read_bytes()
    with pytest.raises(cst.ParserSyntaxError) as excinfo:
        cst.parse_module(data)
    error = excinfo.value
    assert (error.raw_line, error.raw_column) == builder.PARSER_SYNTAX_ERROR_AT
    assert (error.editor_line, error.editor_column) == builder.PARSER_SYNTAX_ERROR_EDITOR_AT
    assert builder.PARSER_SYNTAX_ERROR_AT != builder.PARSER_SYNTAX_ERROR_EDITOR_AT


def test_the_two_gates_blame_different_lines_of_the_same_file() -> None:
    """`compile()` names the line the bracket opened, libcst two lines later, so the gate order
    (ADR-017 D1) decides the reported line."""
    data = (ENCODING_DIR / builder.LIBCST_REFUSES).read_bytes()
    with pytest.raises(SyntaxError) as excinfo:
        compile(data, builder.LIBCST_REFUSES, "exec")
    assert excinfo.value.lineno == builder.PARSER_SYNTAX_ERROR_COMPILE_LINENO
    assert excinfo.value.lineno != builder.PARSER_SYNTAX_ERROR_AT[0]


def test_check_mode_reports_success_on_the_committed_tree() -> None:
    assert builder.verify(GENERATED) is True


def test_check_mode_fails_when_a_fixture_is_normalised(tmp_path: Path) -> None:
    damaged = dict(GENERATED)
    damaged["bare_cr.py"] = GENERATED["bare_cr.py"].replace(b"\r", b"\n")
    for name, data in damaged.items():
        (tmp_path / name).write_bytes(data)

    original_here = builder.HERE
    try:
        builder.HERE = tmp_path
        assert builder.verify(GENERATED) is False
    finally:
        builder.HERE = original_here


@pytest.mark.parametrize("source", sorted(builder.PAIRS))
def test_the_answer_key_keeps_the_inputs_byte_shape(source: str) -> None:
    """Read from the bytes, not via libcst, so the answer does not depend on the code under test."""
    answer = builder.PAIRS[source]
    before = builder.byte_shape((ENCODING_DIR / source).read_bytes())
    after = builder.byte_shape((ENCODING_DIR / answer).read_bytes())
    assert before == after, (
        f"{answer} does not have the byte shape of {source}: {before} vs {after}. "
        f"A migration must not change the line terminator, the PEP 263 cookie, the BOM "
        f"or whether the file ends in a newline."
    )


def test_only_the_three_refused_files_have_no_answer_key() -> None:
    """No key claims "unchanged": all three bail (`roundtrip_mismatch`, `input_does_not_parse`
    from either gate), so `obelize fix --apply` leaves them byte for byte."""
    inputs = {name for name in GENERATED if not name.endswith(".after.py")}
    assert inputs - set(builder.PAIRS) == {
        "bare_cr.py",
        "parser_syntax_error.py",
        "python2.py",
    }
    assert set(builder.PAIRS.values()) == {n for n in GENERATED if n.endswith(".after.py")}


def test_check_mode_fails_when_an_answer_key_normalises_the_terminator(tmp_path: Path) -> None:
    """The failure the keys exist to catch: a rewrite that silently emits LF."""
    damaged = dict(GENERATED)
    damaged["crlf.after.py"] = GENERATED["crlf.after.py"].replace(b"\r\n", b"\n")
    for name, data in damaged.items():
        (tmp_path / name).write_bytes(data)

    original_here = builder.HERE
    try:
        builder.HERE = tmp_path
        assert builder.verify(damaged) is False
    finally:
        builder.HERE = original_here


def test_the_generators_must_not_report_line_still_points_at_the_literal() -> None:
    """The pinned line drifts when `_build.py` is edited; a row off the literal tests nothing."""
    import yaml

    ground_truth = yaml.safe_load((ENCODING_DIR / "ground_truth.yaml").read_text(encoding="utf-8"))
    rows = [r for r in ground_truth["must_not_report"] if r["file"] == "_build.py"]
    assert len(rows) == 1, rows

    lines = BUILDER.read_bytes().splitlines()
    pinned = lines[rows[0]["line"] - 1]
    assert b"import google.generativeai as genai" in pinned, (
        f"ground_truth.yaml points must_not_report at _build.py:{rows[0]['line']}, which is "
        f"{pinned.decode('utf-8', 'replace')!r}. Re-point it at the first line of the generator "
        f"that carries the legacy import literal."
    )
